# Generated by Django 3.0.2 on 2023-05-05 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_auto_20230309_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('period', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('half_year', 'Полгода'), ('year', 'Год')], max_length=9, verbose_name='Период')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='organization.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('is_active', models.BooleanField(verbose_name='Вкл/Выкл')),
                ('auto_renewal', models.BooleanField(verbose_name='Автопродление')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organization.Organization', verbose_name='Организация')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tariffs.Tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('organization',), name='unique_org_subs_active'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('tariff', 'organization'), name='unique_tariff_org_subs'),
        ),
    ]
