# Generated by Django 3.0.2 on 2022-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220302_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
