# Generated by Django 3.0.2 on 2022-03-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20220309_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkResults',
        ),
    ]
