# Generated by Django 3.0.2 on 2022-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_delete_workresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
