# Generated by Django 3.0.2 on 2023-10-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20230215_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
