# Generated by Django 3.0.2 on 2024-02-07 12:41

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_is_auto_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('counter', 'Счетчик'), ('controller', 'УК'), ('auditor', 'Аудитор'), ('storage', 'Сотрудник склада')], max_length=10, verbose_name='Роль'), size=None, verbose_name='Роли'),
        ),
    ]
