# Generated by Django 3.0.2 on 2024-02-08 14:05

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20240207_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('counter', 'Счетчик'), ('auditor', 'Аудитор'), ('auditor_external', 'Внешний аудитор'), ('storage', 'Сотрудник склада')], max_length=16, verbose_name='Роль'), size=None, verbose_name='Роли'),
        ),
    ]
