# Generated by Django 3.0.2 on 2022-03-09 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_auto_20220301_1753'),
        ('zone', '0005_auto_20220305_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('vendor_code', models.CharField(max_length=25, verbose_name='Код товара')),
                ('barcode', models.CharField(max_length=48, verbose_name='Штрих-код')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('remainder', models.PositiveSmallIntegerField(default=0, verbose_name='Остаток')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='project.Project', verbose_name='Проект')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='zone.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
    ]
