# Generated by Django 3.0.2 on 2022-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220516_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
