# Generated by Django 3.0.2 on 2022-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220705_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код товара'),
        ),
    ]
