# Generated by Django 3.0.2 on 2022-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220705_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.BigIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
