# Generated by Django 3.0.2 on 2022-12-21 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20221221_2115'),
        ('product', '0011_auto_20220706_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOfProjectProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('products_file', models.FileField(upload_to='file_of_products_upload')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_of_products', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
