# Generated by Django 3.0.2 on 2023-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20221222_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='scanned_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сканирования товара'),
        ),
    ]
