# Generated by Django 3.0.2 on 2023-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20230314_1102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='product_pro_id_06b227_idx'),
        ),
    ]
