# Generated by Django 3.0.2 on 2023-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20230405_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='am',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Акцизная марка'),
        ),
    ]
