# Generated by Django 3.0.2 on 2023-10-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20231019_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileofprojectproducts',
            options={'verbose_name': 'Сгенерированный .txt-файл с товарами', 'verbose_name_plural': 'Сгенерированные .txt-файлы с товарами'},
        ),
    ]
