# Generated by Django 3.0.2 on 2023-10-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20231025_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproduct',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11, verbose_name='Колличество'),
        ),
    ]
