# Generated by Django 3.0.2 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20231025_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='is_weight',
            field=models.BooleanField(default=False, verbose_name='Весовой'),
        ),
    ]
