# Generated by Django 3.0.2 on 2024-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20231213_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, null=True, verbose_name='Остаток'),
        ),
    ]
