# Generated by Django 3.0.2 on 2024-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20240109_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='dm',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Датаматрикс'),
        ),
    ]
