# Generated by Django 3.0.2 on 2024-03-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20240326_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproduct',
            name='dm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Датаматрикс'),
        ),
    ]
