# Generated by Django 3.0.2 on 2024-04-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20240131_1756'),
        ('product', '0034_auto_20240401_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproducttitleattribute',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_attrs', to='project.Project', verbose_name='Проект'),
        ),
    ]
