# Generated by Django 3.0.2 on 2024-04-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_additionalproducttitleattribute_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalproducttitleattribute',
            options={'verbose_name': 'Дополнительный атрибут названия товара', 'verbose_name_plural': 'Дополнительные атрибуты названия товара'},
        ),
        migrations.RemoveIndex(
            model_name='additionalproducttitleattribute',
            name='product_add_product_d293ef_idx',
        ),
        migrations.RemoveField(
            model_name='additionalproducttitleattribute',
            name='product_barcode',
        ),
        migrations.AddField(
            model_name='additionalproducttitleattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_attrs', to='product.Product', verbose_name='Продукт'),
        ),
    ]
