# Generated by Django 5.0.4 on 2024-08-06 11:55

import apps.document.models.snils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('file', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpassport',
            name='citizenship',
            field=models.CharField(max_length=40, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='date_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='department_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Код подразделения должен состоять из 6 цифр', regex='^[0-9]{6}$')], verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='issued_by',
            field=models.TextField(verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='number',
            field=models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Номер должен состоять из 6 цифр', regex='^[0-9]{6}$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='place_of_birth',
            field=models.TextField(verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='series',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Серия должна состоять из 4 цифр', regex='^[0-9]{4}$')], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='historicalregistration',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='historicalsnils',
            name='value',
            field=models.TextField(db_index=True, validators=[apps.document.models.snils.validators.SNILSValidator()], verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inn_documents', to='file.file', verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='citizenship',
            field=models.CharField(max_length=40, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='department_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Код подразделения должен состоять из 6 цифр', regex='^[0-9]{6}$')], verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_documents', to='file.file', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.TextField(verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Номер должен состоять из 6 цифр', regex='^[0-9]{6}$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='place_of_birth',
            field=models.TextField(verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Серия должна состоять из 4 цифр', regex='^[0-9]{4}$')], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='file',
            field=models.ManyToManyField(related_name='registration_documents', to='file.file', verbose_name='Страницы с регистрацией'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='selfie',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selfie_documents', to='file.file', verbose_name='файл селфи'),
        ),
        migrations.AlterField(
            model_name='selfierecognition',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selfie_recognitions', to='document.passport', verbose_name='паспорт'),
        ),
        migrations.AlterField(
            model_name='selfierecognition',
            name='status',
            field=models.CharField(choices=[('recognition_succeeded', 'Успешная автоматическая проверка'), ('recognition_failed', 'Ошибка автоматическай проверки')], max_length=21, verbose_name='статус селфи'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='value',
            field=models.TextField(unique=True, validators=[apps.document.models.snils.validators.SNILSValidator()], verbose_name='Значение'),
        ),
    ]
