# Generated by Django 5.0.4 on 2024-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_historicalpassport_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpassport',
            name='registration_address',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='registration_address',
        ),
        migrations.AddField(
            model_name='selfierecognition',
            name='match_confirmation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подтверждение соответствия селфи с паспортом'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
