# Generated by Django 5.0.4 on 2024-08-12 15:39

import apps.document.models.snils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_historicalpassport_registration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsnils',
            name='value',
            field=models.CharField(db_index=True, max_length=11, validators=[apps.document.models.snils.validators.SNILSValidator()], verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='value',
            field=models.CharField(max_length=11, unique=True, validators=[apps.document.models.snils.validators.SNILSValidator()], verbose_name='Значение'),
        ),
    ]
