# Generated by Django 5.0.4 on 2024-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_historicalpassport_registration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinn',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalregistration',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalselfie',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalsnils',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='selfie',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='created', max_length=8, verbose_name='Статус'),
        ),
    ]
