# Generated by Django 5.0.4 on 2024-08-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_historicalinn_status_and_more'),
        ('document', '0004_alter_historicalsnils_value_alter_snils_value'),
    ]

    operations = [
    ]
