# Generated by Django 5.0.4 on 2024-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_merge_20240812_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinn',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='historicalpassport',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='historicalselfie',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='historicalsnils',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='inn',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='passport',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='selfie',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='snils',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина отклонения'),
        ),
    ]
