# Generated by Django 5.0.4 on 2024-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_historicalinn_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalselfie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical селфи с паспортом', 'verbose_name_plural': 'historical селфи с паспортом'},
        ),
        migrations.AlterModelOptions(
            name='selfie',
            options={'ordering': ('-created_at',), 'verbose_name': 'селфи с паспортом', 'verbose_name_plural': 'селфи с паспортом'},
        ),
        migrations.AddField(
            model_name='historicalpassport',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpassport',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpassport',
            name='patronymic',
            field=models.CharField(default='', max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='patronymic',
            field=models.CharField(default='', max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
