# Generated by Django 5.0.4 on 2024-09-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_historicalselfie_options_alter_selfie_options_and_more'),
        ('file', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inn',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inn_documents', to='file.file', verbose_name='ИНН'),
        ),
    ]
