# Generated by Django 5.0.4 on 2024-10-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_inn_file'),
        ('file', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passport_documents', to='file.file', verbose_name='Паспорт'),
        ),
    ]
