# Generated by Django 5.0.4 on 2024-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_passport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinn',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalpassport',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalregistration',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalselfie',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalsnils',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='selfie',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Статус'),
        ),
    ]
