# Generated by Django 5.0.4 on 2024-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('user', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='users', to='regions.region', verbose_name='Регионы'),
        ),
    ]
