# Generated by Django 5.0.4 on 2024-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('user', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users', to='projects.project', verbose_name='Проекты'),
        ),
    ]
