# Generated by Django 5.0.4 on 2024-08-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_projects'),
        ('user', '0004_user_regions'),
    ]

    operations = [
    ]
