# Generated by Django 5.0.4 on 2024-08-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_department'),
        ('user', '0005_merge_0004_user_projects_0004_user_regions'),
    ]

    operations = [
    ]
