# Generated by Django 5.0.4 on 2024-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20240821_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Мастер'), ('applicant', 'Аппликант'), ('applicant_confirmed', 'Аппликант подтвержденный'), ('candidate', 'Кандидат'), ('emoloyee', 'Сотрудник'), ('supervisor', 'Супервизор'), ('dismissed', 'Уволенный')], default='applicant', max_length=19, verbose_name='Роль'),
        ),
    ]
