# Generated by Django 5.0.4 on 2024-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_is_send_arketa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_send_arketa',
        ),
        migrations.AddField(
            model_name='user',
            name='arketa_user_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Id пользователя в аркете'),
        ),
    ]
