# Generated by Django 5.0.4 on 2025-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_is_send_arketa_user_arketa_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doc_status',
            field=models.CharField(choices=[('approval', 'Проверка'), ('accept', 'Подтвержден'), ('decline', 'Отклонен')], default='approval', max_length=8, verbose_name='Общий статус документов пользователя'),
        ),
    ]
