# Generated by Django 3.0.2 on 2022-03-02 06:49

import apps.helpers.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_auto_20220301_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('roles', apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('counter', 'Счетчик'), ('auditor', 'Аудитор'), ('storage', 'Сотрудник склада')], max_length=7, verbose_name='Роль'), size=None, verbose_name='Роли')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-serial_number', 'project__title'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('counter_scan', models.PositiveSmallIntegerField(default=0, verbose_name='С.Скан')),
                ('counter_controller', models.PositiveSmallIntegerField(default=0, verbose_name='С.УК')),
                ('auditor_scan', models.PositiveSmallIntegerField(default=0, verbose_name='А.Скан')),
                ('auditor_controller', models.PositiveSmallIntegerField(default=0, verbose_name='А.УК')),
                ('storage', models.PositiveSmallIntegerField(default=0, verbose_name='Сотрудник склада')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Результат работы',
                'verbose_name_plural': 'Результаты работы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('project', 'serial_number'), name='Порядковый номер сотрудника в рамках проекта'),
        ),
    ]
