# Generated by Django 3.0.2 on 2023-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='serial_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
