# Generated by Django 3.0.2 on 2024-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20231023_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_auto_assignment',
            field=models.BooleanField(default=False, verbose_name='Автоназначение'),
        ),
    ]
