# Generated by Django 3.0.2 on 2023-05-29 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('link', models.CharField(max_length=127, verbose_name='Ссылка на канал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Парсинг активен')),
            ],
            options={
                'verbose_name': 'Канал для парсинга',
                'verbose_name_plural': 'Каналы для парсинга',
            },
        ),
    ]
