# Generated by Django 3.0.2 on 2023-05-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Канал для парсинга', 'verbose_name_plural': 'Каналы для парсинга'},
        ),
    ]
