# Generated by Django 3.0.2 on 2023-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20230529_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(max_length=127, unique=True, verbose_name='Ссылка на канал'),
        ),
    ]
