# Generated by Django 3.0.2 on 2021-05-20 19:37

import uuid

import apps.file.models
import apps.file.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('image', models.FileField(upload_to=apps.file.models.directory_path, validators=[apps.file.validator.ImageExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'webp', 'png', 'gif'))])),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
