# Generated by Django 3.0.2 on 2023-11-21 14:26

import apps.file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.file.models.directory_path),
        ),
    ]
