# Generated by Django 3.0.2 on 2023-05-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20230529_1319'),
        ('file', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='message.Message'),
        ),
    ]
