INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.gis',

    'corsheaders',
    'django_filters',
    'phonenumber_field',
    'drf_yasg',
    'rest_framework',
    'drf_extra_fields',
    'fcm_django',
    'constance',
    'constance.backends.database',
    'storages',
    'django_ckeditor_5',
    'rest_framework_simplejwt',
    'simple_history',
    'drf_standardized_errors',

    'apps.user',
    'apps.file',
    'apps.faq',
    'apps.address',
    'apps.news',
    'apps.departments',
    'apps.regions',
    'apps.document',
    'apps.projects',
    'apps.stories',
    'apps.promotion',
    'apps.survey',
    'apps.arketa',
]
