# Generated by Django 5.0.4 on 2024-08-21 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_top', models.BooleanField(default=False, verbose_name='Закрепленная новость')),
                ('attachments', models.ManyToManyField(blank=True, related_name='news', to='file.file', verbose_name='Вложения')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='file.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
