# Generated by Django 5.0.4 on 2024-08-22 11:03

import apps.helpers.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0001_initial'),
        ('news', '0001_initial'),
        ('projects', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNewsMailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_push', models.BooleanField(default=False, verbose_name='Отправка пуш-уведомления')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_mailing', to='news.news', verbose_name='Новость')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Базовая рассылка новостей',
                'verbose_name_plural': 'Базовые рассылки новостей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsMailingUserRole',
            fields=[
                ('basenewsmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.basenewsmailing')),
                ('roles', apps.helpers.models.ChoiceArrayField(base_field=models.CharField(choices=[('applicant', 'Аппликант'), ('employee', 'Сотрудник'), ('supervisor', 'Супервайзер')], max_length=10, verbose_name='Роль'), size=None, verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Новостная рассылка по ролям',
                'verbose_name_plural': 'Новостные рассылки по ролям',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('news.basenewsmailing',),
        ),
        migrations.CreateModel(
            name='NewsMailingDepartment',
            fields=[
                ('basenewsmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.basenewsmailing')),
                ('departments', models.ManyToManyField(related_name='news_mailing', to='departments.department', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Новостная рассылка по департаментам',
                'verbose_name_plural': 'Новостные рассылки по департаментам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('news.basenewsmailing',),
        ),
        migrations.CreateModel(
            name='NewsMailingProject',
            fields=[
                ('basenewsmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.basenewsmailing')),
                ('projects', models.ManyToManyField(related_name='news_mailing', to='projects.project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Новостная рассылка по проектам',
                'verbose_name_plural': 'Новостные рассылки по проектам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('news.basenewsmailing',),
        ),
        migrations.CreateModel(
            name='NewsMailingRegion',
            fields=[
                ('basenewsmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.basenewsmailing')),
                ('regions', models.ManyToManyField(related_name='news_mailing', to='regions.region', verbose_name='Регионы')),
            ],
            options={
                'verbose_name': 'Новостная рассылка по регионам',
                'verbose_name_plural': 'Новостные рассылки по регионам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('news.basenewsmailing',),
        ),
    ]
