# Generated by Django 5.0.4 on 2024-08-22 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_basenewsmailing_newsmailinguserrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.CreateModel(
            name='NewsEmoji',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('emoji_type', models.CharField(choices=[('smirk', 'Ухмылка'), ('thumb_up', 'Палец вверх'), ('thumb_down', 'Палец вниз'), ('fire', 'Огонь'), ('heart', 'Сердце'), ('shock', 'Удивление')], max_length=10, verbose_name='Тип эмодзи')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_emoji', to='news.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_emoji', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эмодзи новости',
                'verbose_name_plural': 'Эмодзи новостей',
            },
        ),
        migrations.AddConstraint(
            model_name='newsemoji',
            constraint=models.UniqueConstraint(fields=('news', 'user'), name='Эмодзи юзера на новость'),
        ),
    ]
