# Generated by Django 5.0.4 on 2024-09-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_image'),
        ('news', '0004_newsread_newsread_просмотр_новости_пользователем'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover',
        ),
        migrations.AddField(
            model_name='news',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_main_news', to='file.image', verbose_name='Превью для главной'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_standard_news', to='file.image', verbose_name='Превью стандарт'),
        ),
    ]
