# Generated by Django 5.0.4 on 2024-09-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_image'),
        ('news', '0005_remove_news_cover_news_is_main_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_standard_news', to='file.image', verbose_name='Превью стандарт'),
        ),
    ]
