# Generated by Django 5.0.4 on 2024-09-24 14:19

import apps.helpers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_preview_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmailinguserrole',
            name='roles',
            field=apps.helpers.models.ChoiceArrayField(base_field=models.CharField(choices=[('applicant', 'Аппликант'), ('employee', 'Сотрудник'), ('supervisor', 'Супервизор'), ('candidate', 'Кандидат'), ('dismissed', 'Уволенный'), ('applicant_confirmed', 'Аппликант подтвержденный')], max_length=19, verbose_name='Роль'), size=None, verbose_name='Роли'),
        ),
    ]
