INSTALLED_APPS = [
    'channels',
    'daphne',

    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',

    'corsheaders',
    'django_filters',
    'phonenumber_field',
    'drf_yasg',
    'rest_framework',
    'drf_extra_fields',
    'fcm_django',
    'constance',
    'constance.backends.database',
    'storages',
    'ckeditor',
    'rest_framework_simplejwt',

    'apps.user',
    'apps.file',
    'apps.project',
    'apps.template',
    'apps.employee',
    'apps.zone',
    'apps.task',
    'apps.product',
    'apps.terminal',
    'apps.event',
    'apps.document',
    'apps.reports',
    'apps.changelog',
]
