# Generated by Django 3.0.2 on 2022-02-24 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_terminalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalsettings',
            name='check_am',
            field=models.CharField(blank=True, choices=[('without_am_check', 'Без проверки AM'), ('only_am_check', 'Только наличие AM'), ('conformity_am', 'Соответствие AM и ШК')], max_length=16, null=True, verbose_name='Проверка АМ'),
        ),
        migrations.CreateModel(
            name='RMMSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_zones_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во автоназначенных зон')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пароль для редактирования документа')),
                ('norm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Норма счётчика')),
                ('extended_tasks', models.NullBooleanField(verbose_name='Расширенный механизм заданий')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_settings', to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Настройки параметров РММ',
                'verbose_name_plural': 'Настройки параметров РММ',
            },
        ),
    ]
