# Generated by Django 3.0.2 on 2022-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220301_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmmsettings',
            name='auto_zones_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во автоназначенных зон'),
        ),
        migrations.AlterField(
            model_name='rmmsettings',
            name='extended_tasks',
            field=models.NullBooleanField(default=False, verbose_name='Расширенный механизм заданий'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='check_am',
            field=models.CharField(choices=[('without_am_check', 'Без проверки AM'), ('only_am_check', 'Только наличие AM'), ('conformity_am', 'Соответствие AM и ШК')], default='without_am_check', max_length=16, verbose_name='Проверка АМ'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='check_dm',
            field=models.CharField(choices=[('without_dm_check', 'Без проверки DM'), ('only_dm_check', 'Только наличие DM'), ('conformity_dm', 'Соответствие DM и ШК')], default='without_dm_check', max_length=16, verbose_name='Проверка DM'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='compliance_codes',
            field=models.CharField(default='0-000;1-770;2-780,3-020;4-021;5-022;6-023;7-024;8-025;9-026', max_length=100, verbose_name='Коды соответствия ШК х5'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='error_correction',
            field=models.NullBooleanField(default=False, verbose_name='Исправление ошибок'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='issuing_task',
            field=models.CharField(choices=[('least_loaded_user', 'Наименее загруженному пользователю'), ('current_user', 'Текущему пользователю')], default='least_loaded_user', max_length=17, verbose_name='Выдача задания для УК'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='length_barcode_pallets',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длина ШК Паллеты'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='product_name',
            field=models.CharField(choices=[('by_product_code', 'По коду товара'), ('by_barcode', 'По штрих-коду')], default='by_product_code', max_length=15, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='recalculation_discrepancy',
            field=models.CharField(choices=[('scan', 'Скан'), ('controller', 'УК')], default='scan', max_length=10, verbose_name='Пересчет при расхождении'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='suspicious_barcodes_amount',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Подозрительное кол-во для ШК'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='trimming_barcode',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Обрезка штрих-кода с начала и с конца'),
        ),
        migrations.AlterField(
            model_name='terminalsettings',
            name='unknown_barcode',
            field=models.CharField(choices=[('allow', 'Разрешать'), ('disallow', 'Запрещать')], default='disallow', max_length=8, verbose_name='Неизвестный штрих-код'),
        ),
    ]
