# Generated by Django 3.0.2 on 2022-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_terminalsettings_search_by_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmmsettings',
            name='auto_zones_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во автоназначаемых зон'),
        ),
    ]
