# Generated by Django 3.0.2 on 2022-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_auto_assign_enbale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='auto_assign_enbale',
            field=models.BooleanField(default=False, verbose_name='Включено автоназначение задач С.Скан'),
        ),
    ]
