# Generated by Django 3.0.2 on 2022-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20221221_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accounting_without_yk',
            field=models.BooleanField(default=False, verbose_name='Учет без УК'),
        ),
    ]
