# Generated by Django 3.0.2 on 2023-10-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20230209_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
