# Generated by Django 3.0.2 on 2023-11-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20231023_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='manual_input_quantity',
            field=models.BooleanField(default=False, verbose_name='Ручной ввод кол-ва'),
        ),
    ]
