# Generated by Django 3.0.2 on 2024-01-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_project_auto_assign_enbale'),
        ('project', '0020_auto_20240122_1632'),
    ]

    operations = [
    ]
