# Generated by Django 3.0.2 on 2024-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_merge_20240124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_assign_enbale',
            field=models.BooleanField(default=False, verbose_name='Включено автоназначение задач для Скан'),
        ),
    ]
