# Generated by Django 3.0.2 on 2024-03-14 09:52

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0018_auto_20240313_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('price', 'Цена товара'), ('remainder', 'Остаток'), ('remainder_2', 'Остаток 2'), ('measure', 'Единица измерения'), ('name_sk', 'Название по ШК'), ('am', 'Признак акцизной марки'), ('dm', 'ДатаМатрик(DataMatrix)'), ('zone_code', 'Код Зоны'), ('zone_name', 'Наименование Зоны'), ('store_number', 'Номер магазина'), ('additional_product_name_1', 'Доп. наименование товара 1'), ('additional_product_name_2', 'Доп. наименование товара 2'), ('additional_product_name_3', 'Доп. наименование товара 3'), ('product_group', 'Группа товара'), ('trademark', 'Торговая марка'), ('size', 'Размер'), ('color', 'Цвет'), ('required_marking', 'Обязательная маркировка'), ('locked_date', 'Дата запрета оборота'), ('name_sk_1', 'Название по ШК 1'), ('name_sk_2', 'Название по ШК 2'), ('name_sk_3', 'Название по ШК 3'), ('price_sk', 'Цена по ШК'), ('storage_code', 'Код склада'), ('storage_place_code', 'Код места хранения'), ('storage_place_type', 'Тип места хранения'), ('pers_number', 'Табельный номер'), ('counter_status', 'Статус счётчика'), ('full_name', 'ФИО'), ('serial_number', 'Порядковый номер сотрудника')], max_length=25, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
        migrations.AlterField(
            model_name='templateexport',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('zone_name', 'Наименование Зоны'), ('zone_number', 'Номер зоны'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('price', 'Цена товара'), ('remainder_barcode', 'Остаток по штрихкоду'), ('discrepancy', 'Расхождение'), ('discrepancy_decimal', 'Расхождение с десятичной частью'), ('count_scanned_product', 'Количество отсканированных товаров'), ('count', 'Количество'), ('counter_code', 'Код счетчика'), ('data_matrix_code', 'Код DataMatrix'), ('store_number', 'Номер магазина'), ('product_group', 'Группа товара'), ('storage_code', 'Код склада'), ('trademark', 'Торговая марка'), ('size', 'Размер'), ('color', 'Цвет'), ('box_number', 'Номер короба'), ('pallet_number', 'Номер паллеты'), ('additional_product_name_1', 'Доп. наименование товара 1'), ('additional_product_name_2', 'Доп. наименование товара 2'), ('additional_product_name_3', 'Доп. наименование товара 3'), ('name_sk', 'Название по ШК'), ('name_sk_1', 'Название по ШК 1'), ('name_sk_2', 'Название по ШК 2'), ('name_sk_3', 'Название по ШК 3'), ('price_sk', 'Цена по ШК')], max_length=25, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
    ]
