# Generated by Django 3.0.2 on 2024-03-26 09:30

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0023_auto_20240325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('pin_not_download', 'Не загружать'), ('pin_not_download_1', 'Не загружать'), ('pin_not_download_2', 'Не загружать'), ('pin_not_download_3', 'Не загружать'), ('pin_not_download_4', 'Не загружать'), ('pin_not_download_5', 'Не загружать'), ('pin_not_download_6', 'Не загружать'), ('pin_not_download_7', 'Не загружать'), ('pin_not_download_8', 'Не загружать'), ('pin_not_download_9', 'Не загружать'), ('pin_not_download_10', 'Не загружать'), ('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('price', 'Цена товара'), ('remainder', 'Остаток'), ('remainder_2', 'Остаток 2'), ('measure', 'Единица измерения'), ('name_sk', 'Название по ШК'), ('am', 'Признак акцизной марки'), ('dm', 'ДатаМатрик(DataMatrix)'), ('zone_code', 'Код Зоны'), ('zone_name', 'Наименование Зоны'), ('store_number', 'Номер магазина (для РеТрейдинг)')], max_length=19, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
    ]
