# Generated by Django 3.0.2 on 2024-03-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0027_auto_20240329_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='is_reusable',
            field=models.BooleanField(db_index=True, default=False, help_text='Можно ли данное поле использовать несколько раз', verbose_name='Многоразовое?'),
        ),
    ]
