# Generated by Django 3.0.2 on 2024-04-03 06:00

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0028_templatefield_is_reusable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('pin_not_download', 'Не загружать'), ('pin_not_download_1', 'Не загружать'), ('pin_not_download_2', 'Не загружать'), ('pin_not_download_3', 'Не загружать'), ('pin_not_download_4', 'Не загружать'), ('pin_not_download_5', 'Не загружать'), ('pin_not_download_6', 'Не загружать'), ('pin_not_download_7', 'Не загружать'), ('pin_not_download_8', 'Не загружать'), ('pin_not_download_9', 'Не загружать'), ('pin_not_download_10', 'Не загружать'), ('pin_additional_title', 'Доп наименование товара'), ('pin_additional_title_1', 'Доп наименование товара 1'), ('pin_additional_title_2', 'Доп наименование товара 2'), ('pin_additional_title_3', 'Доп наименование товара 3'), ('pin_additional_title_4', 'Доп наименование товара 4'), ('pin_additional_title_5', 'Доп наименование товара 5'), ('pin_additional_title_6', 'Доп наименование товара 6'), ('pin_additional_title_7', 'Доп наименование товара 7'), ('pin_additional_title_8', 'Доп наименование товара 8'), ('pin_additional_title_9', 'Доп наименование товара 9'), ('pin_additional_title_10', 'Доп наименование товара 10'), ('pin_hidden_title_attr', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_1', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_2', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_3', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_4', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_5', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_6', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_7', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_8', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_9', 'Скрытый аттрибут названия'), ('pin_hidden_title_attr_10', 'Скрытый аттрибут названия'), ('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('price', 'Цена товара'), ('remainder', 'Остаток'), ('remainder_2', 'Остаток 2'), ('measure', 'Единица измерения'), ('name_sk', 'Название по ШК'), ('am', 'Признак акцизной марки'), ('dm', 'ДатаМатрик(DataMatrix)'), ('zone_code', 'Код Зоны'), ('zone_name', 'Наименование Зоны'), ('store_number', 'Номер магазина (для РеТрейдинг)')], max_length=24, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
    ]
