# Generated by Django 3.2 on 2024-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0042_alter_templateexport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexport',
            name='single_export',
            field=models.BooleanField(default=False, verbose_name='Поединичная выгрузка'),
        ),
    ]
