# Generated by Django 3.2 on 2024-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0046_alter_templateexport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexport',
            name='is_product_find_by_code',
            field=models.BooleanField(default=False, help_text='Нужно ли добавлять в выгрузку товары, найденные по коду', verbose_name='Товары, найденные по коду'),
        ),
        migrations.AddField(
            model_name='templateexport',
            name='zone_number_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер зоны, до'),
        ),
        migrations.AddField(
            model_name='templateexport',
            name='zone_number_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер зоны, от'),
        ),
    ]
