# Generated by Django 3.2 on 2024-08-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0047_auto_20240827_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexport',
            name='zone_number_end',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер зоны, до'),
        ),
    ]
