# Generated by Django 3.2 on 2024-08-27 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0048_alter_templateexport_zone_number_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexport',
            name='zone_number_start',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер зоны, от'),
        ),
    ]
