# Generated by Django 3.2 on 2024-08-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0049_alter_templateexport_zone_number_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateexport',
            old_name='is_product_find_by_code',
            new_name='is_products_find_by_code',
        ),
    ]
