# Generated by Django 3.2 on 2024-08-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0050_rename_is_product_find_by_code_templateexport_is_products_find_by_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexport',
            name='is_products_find_by_qr_code',
            field=models.BooleanField(default=False, help_text='Нужно ли добавлять в выгрузку товары, найденные по qr-коду', verbose_name='Товары, найденные по qr-коду'),
        ),
    ]
