# Generated by Django 3.0.2 on 2022-03-31 08:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0012_delete_task'),
        ('terminal', '0001_initial'),
        ('employee', '0007_delete_workresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', models.CharField(choices=[('counter_scan', 'С.Скан'), ('counter_controller', 'С.УК'), ('auditor_scan', 'А.Скан'), ('auditor_controller', 'А.УК'), ('storage', 'Сотрудник склада')], max_length=18, verbose_name='Тип')),
                ('status', models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова')], default='not_ready', max_length=9, verbose_name='Статус')),
                ('result', models.PositiveSmallIntegerField(default=0, verbose_name='Результат')),
                ('barcodes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48, verbose_name='Штрих-код'), blank=True, null=True, size=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employee.Employee', verbose_name='Сотрудник')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='terminal.Terminal', verbose_name='Терминал')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='zone.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('zone', 'employee', 'type'), name='Задание с определенным типом сотрудника на зоне'),
        ),
    ]
