# Generated by Django 3.0.2 on 2022-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='barcodes',
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.PositiveIntegerField(default=0, verbose_name='Результат'),
        ),
    ]
