# Generated by Django 3.0.2 on 2022-08-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0015_zone_code'),
        ('task', '0004_auto_20220824_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='zone.Zone', verbose_name='Зона'),
        ),
    ]
