# Generated by Django 3.0.2 on 2023-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20231023_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова'), ('failed_scan', 'Неудачно, не сошлось')], default='not_ready', max_length=11, verbose_name='Статус'),
        ),
    ]
