# Generated by Django 3.0.2 on 2023-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20231122_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('initialized', 'Инициализирована для работы'), ('worked', 'Проведена работа'), ('failed_scan', 'Неудачный скан, не сошлось'), ('success_scan', 'Удачный скан, сошлось')], default='initialized', max_length=23, verbose_name='Статус'),
        ),
    ]
