# Generated by Django 3.0.2 on 2023-02-08 08:22

import apps.file.models
import apps.file.validator
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file', models.FileField(upload_to=apps.file.models.directory_db_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('json',))])),
            ],
            options={
                'verbose_name': 'Файл БД',
                'verbose_name_plural': 'Файлы БД',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('file', models.FileField(upload_to=apps.file.models.directory_path)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('image', models.FileField(upload_to=apps.file.models.directory_path, validators=[apps.file.validator.ImageExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'webp', 'png', 'gif', 'pdf'))])),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
