# Generated by Django 3.0.2 on 2023-04-13 12:16

import apps.file.models
import apps.file.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=apps.file.models.directory_path, validators=[apps.file.validator.ImageExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'webp', 'png', 'gif', 'pdf', 'svg'))]),
        ),
    ]
