# Generated by Django 3.0.2 on 2023-08-11 14:20

import apps.file.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20230413_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file', models.FileField(upload_to=apps.file.models.directory_path)),
                ('type', models.CharField(choices=[('agreement', 'Согласие на обработку перс. данных'), ('privacy_policy', 'Политика конфиденциальности'), ('terms_of_use', 'Условия пользования')], max_length=14, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Статический файл для апи',
                'verbose_name_plural': 'Статические файлы для апи',
            },
        ),
    ]
