# Generated by Django 3.0.2 on 2022-05-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20220517_1628'),
        ('task', '0002_auto_20220331_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='document.Document'),
        ),
    ]
