# Generated by Django 3.0.2 on 2022-08-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20220816_1615'),
        ('task', '0003_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='employee.Employee', verbose_name='Сотрудник'),
        ),
    ]
