# Generated by Django 3.0.2 on 2022-11-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220824_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document',
        ),
    ]
