# Generated by Django 3.0.2 on 2022-11-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_document'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='Задание с определенным типом сотрудника на зоне',
        ),
    ]
