# Generated by Django 3.0.2 on 2023-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0015_zone_code'),
        ('task', '0007_auto_20221108_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='zone.Zone', verbose_name='Зона'),
        ),
    ]
