# Generated by Django 3.0.2 on 2023-10-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20230121_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова'), ('not_ready_made_another', 'Не готова, зона выполнена другим')], default='not_ready', max_length=22, verbose_name='Статус'),
        ),
    ]
