# Generated by Django 3.0.2 on 2023-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20231025_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('initialized', 'Инициализирована для работы'), ('worked', 'Проведена работа'), ('failed_scan', 'Неудачный скан, не сошлось'), ('success_scan', 'Удачный скан, сошлось'), ('another_one_worked_zone', 'Неактивна, в зоне была отработана другая')], default='initialized', max_length=23, verbose_name='Статус'),
        ),
    ]
