# Generated by Django 3.0.2 on 2023-11-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20231030_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_at', 'zone'), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
