# Generated by Django 3.0.2 on 2024-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20231127_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('counter_scan', 'Счетчик'), ('controller', 'УК'), ('auditor', 'Аудитор'), ('auditor_controller', 'Аудитор УК'), ('auditor_external', 'Внешний Аудитор'), ('storage', 'Сотрудник склада')], max_length=18, verbose_name='Тип'),
        ),
    ]
