# Generated by Django 3.0.2 on 2022-03-02 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_auto_20220302_1750'),
        ('project', '0005_auto_20220301_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('storage_name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('status', models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова')], default='not_ready', max_length=9, verbose_name='Статус')),
                ('employees', models.ManyToManyField(blank=True, related_name='zones', to='employee.Employee', verbose_name='Сотрудники')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'ordering': ('project__title', '-serial_number'),
            },
        ),
    ]
