# Generated by Django 3.0.2 on 2022-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_auto_20220304_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова')], default='not_ready', max_length=9, verbose_name='Статус'),
        ),
    ]
