# Generated by Django 3.0.2 on 2022-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_auto_20220305_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
