# Generated by Django 3.0.2 on 2022-03-25 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0009_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='barcodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48, verbose_name='Штрих-код'), blank=True, null=True, size=None),
        ),
    ]
