# Generated by Django 3.0.2 on 2022-03-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
        ('zone', '0010_task_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='terminal.Terminal', verbose_name='Терминал'),
        ),
    ]
