# Generated by Django 3.0.2 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0013_auto_20220810_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='serial_number',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
