# Generated by Django 3.0.2 on 2023-10-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0015_zone_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('-created_at',), 'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
    ]
