# Generated by Django 3.2 on 2024-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0016_auto_20231023_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='serial_number',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
