# Generated by Django 5.0.4 on 2024-10-30 17:44

import apps.helpers.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0001_initial'),
        ('projects', '0001_initial'),
        ('regions', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSurveyMailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_push', models.BooleanField(default=False, verbose_name='Отправка пуша')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='survey.survey', verbose_name='Опрос')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SurveyMailingRoles',
            fields=[
                ('basesurveymailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.basesurveymailing')),
                ('roles', apps.helpers.models.ChoiceArrayField(base_field=models.CharField(choices=[('applicant', 'Аппликант'), ('employee', 'Сотрудник'), ('supervisor', 'Супервизор'), ('candidate', 'Кандидат'), ('dismissed', 'Уволенный'), ('applicant_confirmed', 'Аппликант подтвержденный')], max_length=19, verbose_name='Роль'), size=None, verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Рассылка опросов по ролям',
                'verbose_name_plural': 'Рассылки опросов по ролям',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.basesurveymailing',),
        ),
        migrations.CreateModel(
            name='SurveyMailingDepartments',
            fields=[
                ('basesurveymailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.basesurveymailing')),
                ('departments', models.ManyToManyField(related_name='survey_mailings', to='departments.department', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Рассылка опросов по департаментам',
                'verbose_name_plural': 'Рассылки опросов по департаментам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.basesurveymailing',),
        ),
        migrations.CreateModel(
            name='SurveyMailingProjects',
            fields=[
                ('basesurveymailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.basesurveymailing')),
                ('projects', models.ManyToManyField(related_name='survey_mailings', to='projects.project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Рассылка опросов по проектам',
                'verbose_name_plural': 'Рассылки опросов по проектам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.basesurveymailing',),
        ),
        migrations.CreateModel(
            name='SurveyMailingRegions',
            fields=[
                ('basesurveymailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.basesurveymailing')),
                ('to_all_regions', models.BooleanField(blank=True, null=True, verbose_name='Рассылка на все регионы')),
                ('regions', models.ManyToManyField(related_name='survey_mailings', to='regions.region', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Рассылка опросов по проектам',
                'verbose_name_plural': 'Рассылки опросов по проектам',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.basesurveymailing',),
        ),
    ]
