# Generated by Django 5.0.4 on 2024-11-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_basesurveymailing_surveymailingroles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveymailingregions',
            options={'base_manager_name': 'objects', 'verbose_name': 'Рассылка опросов по регионам', 'verbose_name_plural': 'Рассылки опросов по регионам'},
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Опрос'),
        ),
    ]
