# Generated by Django 5.0.4 on 2024-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='text',
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
