# Generated by Django 3.0.2 on 2022-03-10 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_auto_20220301_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('db_loading', models.BooleanField(default=False, verbose_name='Загрузка БД')),
                ('last_connect', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время последнего коннекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
                'ordering': ('number',),
            },
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='Номер терминала в рамках проекта'),
        ),
    ]
