# Generated by Django 3.0.2 on 2022-06-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_delete_workresults'),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to='employee.Employee', verbose_name='Сотрудник'),
        ),
    ]
