# Generated by Django 3.0.2 on 2022-09-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_terminal_search_by_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='search_by_product_code',
        ),
    ]
