# Generated by Django 3.0.2 on 2024-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20240205_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мак адрес'),
        ),
    ]
