# Generated by Django 3.0.2 on 2023-02-14 09:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('structure', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Структура')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный шаблон')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='file.Image', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон осмотра',
                'verbose_name_plural': 'Шаблоны осмотра',
                'ordering': ('title',),
            },
        ),
    ]
