# Generated by Django 3.0.2 on 2023-02-27 08:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20230214_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Структура'),
        ),
    ]
