# Generated by Django 3.0.2 on 2023-03-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_auto_20230302_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateClient', verbose_name='Данные клиента'),
        ),
        migrations.AlterField(
            model_name='template',
            name='completeness',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateCompleteness', verbose_name='Комплектность'),
        ),
        migrations.AlterField(
            model_name='template',
            name='damage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateDamage', verbose_name='Повреждения'),
        ),
        migrations.AlterField(
            model_name='template',
            name='documents',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateDocuments', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='template',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateEquipment', verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='template',
            name='lift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateLift', verbose_name='Осмотр на подъемнике'),
        ),
        migrations.AlterField(
            model_name='template',
            name='paintwork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplatePaintwork', verbose_name='ЛКП'),
        ),
        migrations.AlterField(
            model_name='template',
            name='photos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplatePhotos', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='template',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplatePlace', verbose_name='Место осмотра'),
        ),
        migrations.AlterField(
            model_name='template',
            name='signatures',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateSignatures', verbose_name='Подписи'),
        ),
        migrations.AlterField(
            model_name='template',
            name='technical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateTechnical', verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tires',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateTires', verbose_name='Шины'),
        ),
        migrations.AlterField(
            model_name='template',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='template.TemplateVideo', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='templatedocuments',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_documents', to='template.TemplateDocumentsDetail', verbose_name='Подробная настройка документов'),
        ),
        migrations.AlterField(
            model_name='templateequipment',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_equipment', to='template.TemplateEquipmentDetail', verbose_name='Подробная настройка комплектации'),
        ),
        migrations.AlterField(
            model_name='templatephotos',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_photos', to='template.TemplatePhotosDetail', verbose_name='Подробная настройка фотографий'),
        ),
        migrations.AlterField(
            model_name='templatetires',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_tires', to='template.TemplateTiresDetail', verbose_name='Подробная настройка шин'),
        ),
    ]
