# Generated by Django 3.0.2 on 2023-03-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('template', '0006_auto_20230303_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='file.Image', verbose_name='Фото'),
        ),
    ]
