# Generated by Django 3.0.2 on 2023-03-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0007_auto_20230303_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('canceled', 'Отменено'), ('pending', 'В ожидании')], default='pending', max_length=8, verbose_name='Статус')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_invitations', to='template.Template', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение принять шаблон',
                'verbose_name_plural': 'Приглашения принять шаблон',
            },
        ),
        migrations.AddConstraint(
            model_name='templateinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(status='pending'), fields=('user', 'template', 'status'), name='Приглашение принять шаблон без ответа'),
        ),
    ]
