# Generated by Django 3.0.2 on 2023-03-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0008_auto_20230307_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='file.Image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='template',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='templateinvitation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_invitations', to='template.Template', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='templateinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
