# Generated by Django 3.0.2 on 2023-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_auto_20230309_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateclient',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatecompleteness',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatedamage',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatedocuments',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templateequipment',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatelift',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatepaintwork',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatephotos',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templateplace',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatesignatures',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatetechnical',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatetires',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='templatevideo',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
