# Generated by Django 3.0.2 on 2023-04-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_auto_20230406_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_accreditation',
            field=models.BooleanField(default=False, verbose_name='Для аккредитации'),
        ),
    ]
