# Generated by Django 3.0.2 on 2023-08-16 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0012_template_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinvitation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_invitations_owner', to=settings.AUTH_USER_MODEL, verbose_name='Создающий приглашение'),
        ),
        migrations.AlterField(
            model_name='templateinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_invitations_user', to=settings.AUTH_USER_MODEL, verbose_name='приглашаемый пользователь'),
        ),
    ]
