# Generated by Django 3.0.2 on 2023-02-08 08:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты центра')),
                ('fias', models.CharField(max_length=150, verbose_name='fias')),
                ('kladr', models.CharField(max_length=150, verbose_name='kladr')),
                ('inspection_price', models.DecimalField(decimal_places=2, default='100.00', max_digits=19, verbose_name='Цена за осмотр')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='address.City', verbose_name='город')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('title',),
            },
        ),
    ]
