# Generated by Django 3.0.2 on 2023-02-09 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='fias',
        ),
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='kladr',
        ),
        migrations.AddField(
            model_name='city',
            name='fias_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fias_id'),
        ),
    ]
