# Generated by Django 3.0.2 on 2023-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20230209_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='fias_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='fias_id'),
        ),
    ]
