# Generated by Django 3.0.2 on 2022-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',), 'verbose_name': 'Журнал событий', 'verbose_name_plural': 'Журнал событий'},
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(choices=[('for_the_client', 'Для заказчика'), ('products_catalog_load', 'Загружен справочник/каталог'), ('products_catalog_delete', 'Удален справочник/каталог')], default='for_the_client', max_length=23, verbose_name='Комментарий к событию'),
        ),
    ]
