# Generated by Django 3.0.2 on 2022-04-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220428_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(verbose_name='Комментарий к событию'),
        ),
    ]
