# Generated by Django 3.0.2 on 2023-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20220927_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fake_id',
            field=models.IntegerField(default=1),
        ),
    ]
