# Generated by Django 3.0.2 on 2024-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_remove_terminal_search_by_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Мак адрес'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
    ]
