# Generated by Django 3.0.2 on 2022-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('ready', 'Готов'), ('not_ready', 'Не готов')], default='not_ready', max_length=9, verbose_name='Статус'),
        ),
    ]
