# Generated by Django 3.0.2 on 2022-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20220414_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='end_audit_date',
            field=models.DateTimeField(verbose_name='Окончание аудита'),
        ),
        migrations.AlterField(
            model_name='document',
            name='start_audit_date',
            field=models.DateTimeField(verbose_name='Начало аудита'),
        ),
    ]
