# Generated by Django 3.0.2 on 2022-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20221026_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('green', 'Зеленый'), ('red', 'Красный'), ('gray', 'Серый'), ('orange', 'Оранжевый'), ('blue', 'Голубой'), ('violet', 'Фиолетовый'), ('white', 'Белый')], default='red', max_length=6, verbose_name='Цвет'),
        ),
    ]
