# Generated by Django 3.0.2 on 2022-11-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0015_zone_code'),
        ('task', '0006_remove_task_document'),
        ('document', '0009_auto_20221101_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auditor_controller_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor_controller_document', to='task.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='counter_controller_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_controller_document', to='task.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='zone.Zone', verbose_name='Зона'),
        ),
    ]
