# Generated by Django 3.0.2 on 2023-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_document_prev_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='suspicious',
            field=models.BooleanField(default=False, verbose_name='Подозрительный'),
        ),
    ]
