# Generated by Django 3.0.2 on 2023-02-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_document_suspicious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='zone_title',
        ),
    ]
