# Generated by Django 3.0.2 on 2023-10-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_remove_terminal_search_by_product_code'),
        ('document', '0017_auto_20230207_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='terminal.Terminal'),
        ),
    ]
