# Generated by Django 3.0.2 on 2024-02-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20240207_1410'),
        ('document', '0020_document_storage_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='auditor_scan_task',
        ),
        migrations.RemoveField(
            model_name='document',
            name='counter_controller_task',
        ),
        migrations.AddField(
            model_name='document',
            name='auditor_external_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_external_document', to='task.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='auditor_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_document', to='task.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='controller_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_document', to='task.Task'),
        ),
    ]
