from .auditor_report import AuditorReportService, generate_auditor_report_task
from .barcode_matches_report import BarcodeMatchesReportService, generate_barcode_matches_report_task
from .collation_statement_tmc import CollationStatementTMCReportService, generate_collation_statement_report_task
from .differences_report import DifferencesReportService, generate_differences_report_task
from .disc_accounting_quantity_report import (
    DiscAccountingQuantityReportService,
    generate_disc_accounting_quantity_report_task,
)
from .discrepancies_report import DiscrepanciesReportService, generate_discrepancies_report_task
from .errors_report import ErrorsReportService, generate_errors_report_task
from .inv_in_zones_report import InvInZonesReportService, generate_inv_in_zones_report_task
from .inv_ninteen_report import InvNinteenReportService, generate_inv_ninteen_report_task
from .inv_three_report import InvThreeReportService, generate_inv_three_report_task
from .list_of_discrepancies_report import ListOfDiscrepanciesReportService, generate_list_of_discrepancies_report_task
from .not_counted_zones_report import NotCountedZonesReportService, generate_not_counted_zones_report_task
from .not_found_rests_report import NotFoundRestsReportService, generate_not_found_rests_report_task
from .products_in_zones_report import ProductsInZonesReportService, generate_products_in_zones_report
from .suspicious_barcodes_report import SuspiciousBarcodesReportService, generate_suspicious_barcodes_report_task
