# Generated by Django 3.0.2 on 2022-03-31 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220331_1233'),
        ('product', '0003_remove_product_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Колличество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_products', to='product.Product', verbose_name='Товар')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_products', to='task.Task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отсканированный товар',
                'verbose_name_plural': 'Отсканированные товары',
            },
        ),
    ]
