# Generated by Django 3.0.2 on 2022-05-04 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_scannedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
