# Generated by Django 3.0.2 on 2022-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_scannedproduct_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='am',
            field=models.CharField(blank=True, choices=[('counter_scan', 'С.Скан'), ('counter_controller', 'С.УК'), ('auditor_scan', 'А.Скан'), ('auditor_controller', 'А.УК'), ('storage', 'Сотрудник склада')], max_length=18, null=True, verbose_name='Акцизная марка'),
        ),
        migrations.AddField(
            model_name='product',
            name='dm',
            field=models.CharField(blank=True, choices=[('counter_scan', 'С.Скан'), ('counter_controller', 'С.УК'), ('auditor_scan', 'А.Скан'), ('auditor_controller', 'А.УК'), ('storage', 'Сотрудник склада')], max_length=18, null=True, verbose_name='Датаматрикс'),
        ),
    ]
