# Generated by Django 3.0.2 on 2022-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_fileofprojectproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileofprojectproducts',
            name='products_file',
            field=models.CharField(max_length=255),
        ),
    ]
