# Generated by Django 3.0.2 on 2023-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_scannedproduct_scanned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='added_by_product_code',
            field=models.BooleanField(default=False, verbose_name='Найден по коду товара'),
        ),
    ]
