# Generated by Django 3.0.2 on 2023-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_scannedproduct_added_by_product_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_pro_barcode_31e7e5_idx'),
        ),
    ]
