# Generated by Django 3.0.2 on 2023-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20230419_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Название'),
        ),
    ]
