# Generated by Django 3.0.2 on 2023-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20231023_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproduct',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=11, verbose_name='Колличество'),
        ),
    ]
