# Generated by Django 3.0.2 on 2024-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_scannedproduct_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер магазина'),
        ),
    ]
