# Generated by Django 3.0.2 on 2024-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20240314_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Датаматрикс'),
        ),
    ]
