# Generated by Django 3.0.2 on 2024-04-01 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20240327_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProductTitleAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='deleted at')),
                ('product_barcode', models.CharField(max_length=48, verbose_name='Штрих-код продукта')),
                ('content', models.CharField(max_length=200, verbose_name='Содержимое аттрибута')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытый или нет')),
            ],
            options={
                'verbose_name': 'Дополнительный атрибут названия товара',
                'verbose_name_plural': 'Дополнительные атрибуты названия товара',
                'ordering': ('product_barcode',),
            },
        ),
        migrations.AddIndex(
            model_name='additionalproducttitleattribute',
            index=models.Index(fields=['id'], name='product_add_id_019444_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalproducttitleattribute',
            index=models.Index(fields=['product_barcode'], name='product_add_product_d293ef_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalproducttitleattribute',
            index=models.Index(fields=['is_hidden'], name='product_add_is_hidd_0959d5_idx'),
        ),
    ]
