# Generated by Django 3.0.2 on 2024-04-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20240401_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproducttitleattribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='additionalproducttitleattribute',
            name='deleted_at',
        ),
    ]
