# Generated by Django 3.2 on 2024-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20240417_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Размер'),
        ),
    ]
