# Generated by Django 3.2 on 2024-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remainder_2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, null=True, verbose_name='Остаток 2 (виртуальный)'),
        ),
    ]
