# Generated by Django 3.2 on 2024-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_remainder_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='QR-код'),
        ),
    ]
