# Generated by Django 3.2 on 2024-09-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='added_by_qr_code',
            field=models.BooleanField(default=False, verbose_name='Найден по QR-коду товара'),
        ),
    ]
