INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.gis',

    'corsheaders',
    'django_filters',
    'phonenumber_field',
    'drf_yasg',
    'rest_framework',
    'drf_extra_fields',
    'fcm_django',
    'constance',
    'constance.backends.database',
    'storages',
    'ckeditor',

    'apps.user',
    'apps.file',
    'apps.inspector',
    'apps.inspection',
    'apps.organization',
    'apps.template',
    'apps.inspection_task',
    'apps.transaction',
    'apps.car',
    'apps.address',
    'apps.inspector_accreditation',
    'apps.tariffs',
    'apps.notification',
    'apps.devices',
]
