# Generated by Django 3.0.2 on 2023-06-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20230522_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingOrganizationInspectorNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.BaseNotification')),
            ],
            options={
                'verbose_name': 'Уведомление о получении инспектором осмотров по заданию организации',
                'verbose_name_plural': 'Уведомления о получении инспектором осмотров по заданию организации',
                'ordering': ('-created_at',),
            },
            bases=('notification.basenotification',),
        ),
    ]
