# Generated by Django 3.0.2 on 2023-06-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_accreditation', '0006_auto_20230428_1144'),
        ('notification', '0003_issuingorganizationinspectornotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorAccrSuccCompleteNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.BaseNotification')),
                ('accreditation_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accr_success_compl_notifications', to='inspector_accreditation.AccreditationInspection')),
            ],
            options={
                'verbose_name': 'Уведомление о том, что аккредитация успешно пройдена',
                'verbose_name_plural': 'Уведомления о том, что аккредитация успешно пройдена',
                'ordering': ('-created_at',),
            },
            bases=('notification.basenotification',),
        ),
        migrations.CreateModel(
            name='InspectorAccrNewFixesNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.BaseNotification')),
                ('accreditation_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accr_new_fixes_notifications', to='inspector_accreditation.AccreditationInspection')),
            ],
            options={
                'verbose_name': 'Уведомление о том, что пришли корректировки по осмотру в заявке на аккредитию',
                'verbose_name_plural': 'Уведомления о том, что пришли корректировки по осмотру в заявке на аккредитию',
                'ordering': ('-created_at',),
            },
            bases=('notification.basenotification',),
        ),
    ]
