# Generated by Django 3.0.2 on 2023-07-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_inspectoraccrnewfixesnotification_inspectoraccrsucccompletenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantGetTaskWithoutRequisiteNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.BaseNotification')),
            ],
            options={
                'verbose_name': 'Уведомление о том, что невозможно получить задание без заполненных реквизитов',
                'verbose_name_plural': 'Уведомления о том, что невозможно получить задание без заполненных реквизитов',
                'ordering': ('-created_at',),
            },
            bases=('notification.basenotification',),
        ),
    ]
