# Generated by Django 3.0.2 on 2023-08-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0014_auto_20230801_1504'),
        ('notification', '0005_cantgettaskwithoutrequisitenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingorganizationinspectornotification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_org_inspector_notifications', to='inspection_task.InspectionTask'),
        ),
    ]
