# Generated by Django 3.0.2 on 2023-08-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20230704_1228'),
        ('inspection_task', '0014_auto_20230801_1504'),
        ('notification', '0006_issuingorganizationinspectornotification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinvitationnotification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_invitation_notifications', to='organization.Organization'),
        ),
        migrations.CreateModel(
            name='IssuingServiceInspectorNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.BaseNotification')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_service_inspector_notifications', to='inspection_task.InspectionTask')),
            ],
            options={
                'verbose_name': 'Уведомление о получении осмотров инспектором сервиса',
                'verbose_name_plural': 'Уведомления о получении осмотров инспектором сервиса',
                'ordering': ('-created_at',),
            },
            bases=('notification.basenotification',),
        ),
    ]
