# Generated by Django 3.0.2 on 2023-08-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20230809_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
