# Generated by Django 3.0.2 on 2023-02-01 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('model', models.CharField(choices=[('project', 'Проект'), ('rmm_settings', 'Настройки РММ'), ('terminal_settings', 'Настройки терминала'), ('product', 'Продукт')], max_length=17, verbose_name='Модель')),
                ('record_id', models.UUIDField(verbose_name='ID измененной записи')),
                ('action_on_model', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=6, verbose_name='Действие')),
                ('changed_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Измененные данные модели')),
            ],
            options={
                'verbose_name': 'Логи изменений моделей',
                'ordering': ('created_at',),
            },
        ),
    ]
