# Generated by Django 3.0.2 on 2023-02-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_accounting_without_yk'),
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('created_at',), 'verbose_name': 'Лог изменения модели', 'verbose_name_plural': 'Логи изменений моделей'},
        ),
        migrations.AddField(
            model_name='changelog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='project.Project'),
        ),
    ]
