from ..common import env

ASSIST_LOGIN = env('ASSIST_LOGIN', str)
ASSIST_PASSWORD = env('ASSIST_PASSWORD', str)
ASSIST_TEST_HOST = env('ASSIST_TEST_HOST', str)
ASSIST_MERCHANT_ID = env('ASSIST_MERCHANT_ID', str)
ASSIST_FORMAT = env('ASSIST_FORMAT', str)
ASSIST_SALT = env('ASSIST_SALT', str)
ASSIST_SUCCESS_STATUSES = ('Approved',)
ASSIST_ERROR_STATUSES = ('Declined', 'Timeout')
ASSIST_URL_RETURN = env('ASSIST_URL_RETURN', str)
