# Generated by Django 3.0.2 on 2021-05-20 19:37

import apps.helpers.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.helpers.managers.CustomFieldUserManager(username_field_name='phone')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('role', 'роль')], max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
