# Generated by Django 3.0.2 on 2021-05-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210520_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('role', 'роль')], max_length=20, verbose_name='Роль'),
        ),
    ]
