FROM your-registry/templates/image/python:3-8-no-pip

RUN pip install --no-cache-dir --upgrade pip setuptools==49.2.1 && pip install pipenv==2021.5.29
COPY project/Pipfile* /

RUN pipenv install --deploy --system --ignore-pipfile

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY project /app

# fix broken python shell pasting
RUN echo "set enable-bracketed-paste off" >> ~/.inputrc

