# Generated by Django 3.0.2 on 2023-05-29 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0002_auto_20230529_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ext_id', models.PositiveIntegerField(verbose_name='Айди в телеграме')),
                ('text', models.TextField(verbose_name='Текстовое сообщение')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channel.Channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Пост/Сообщение',
                'verbose_name_plural': 'Посты/Сообщения',
            },
        ),
    ]
