# Generated by Django 3.0.2 on 2023-05-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пост/Сообщение', 'verbose_name_plural': 'Посты/Сообщения'},
        ),
    ]
