# Generated by Django 3.0.2 on 2023-06-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20230616_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сообщение'),
        ),
    ]
