# Generated by Django 3.0.2 on 2023-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ext_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время публикации поста'),
        ),
    ]
