# Generated by Django 3.0.2 on 2023-04-10 12:47

import apps.helpers.inn_validator
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20230209_1336'),
        ('inspection_task', '0005_auto_20230314_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorAccreditationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('fio', models.CharField(max_length=63, verbose_name='Фамилия имя')),
                ('inn', models.CharField(max_length=12, validators=[apps.helpers.inn_validator.inn_validator], verbose_name='ИНН')),
                ('work_skills', models.PositiveSmallIntegerField(verbose_name='Опыт работы')),
                ('company', models.CharField(max_length=127, verbose_name='Компания')),
                ('radius', models.PositiveIntegerField(verbose_name='Радиус в км, в котором Инспектор получает заказы')),
                ('availability_thickness_gauge', models.BooleanField(verbose_name='Наличие толщиномера')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_accreditation_requests', to='address.City', verbose_name='Город')),
                ('inspection_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_accreditation_requests', to='inspection_task.InspectionTask', verbose_name='Задание на осмотр')),
            ],
            options={
                'verbose_name': 'Заявка на аккредитацию инспектора',
                'verbose_name_plural': 'Заявки на аккредитацию инспекторов',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
