# Generated by Django 3.0.2 on 2023-04-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20230209_1336'),
        ('template', '0010_auto_20230406_1618'),
        ('inspector_accreditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectoraccreditationrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка на аккредитацию в инспектора', 'verbose_name_plural': 'Заявки на аккредитацию в инспекторов'},
        ),
        migrations.RemoveField(
            model_name='inspectoraccreditationrequest',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='inspectoraccreditationrequest',
            name='inspection_task',
        ),
        migrations.AddField(
            model_name='inspectoraccreditationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_accreditation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='inspectoraccreditationrequest',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accreditation_requests', to='address.City', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='AccreditationInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('dispatcher_check', 'На проверке у диспетчера'), ('troubleshooting', 'Устранение недочетов'), ('inspection_accepted', 'Осмотр принят')], default='dispatcher_check', max_length=19, verbose_name='Статус осмотра')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditation_inspections', to='template.Template', verbose_name='Шаблон осмотра')),
            ],
            options={
                'verbose_name': 'Осмотр в заявке на аккредитацию инспектора',
                'verbose_name_plural': 'Осмотры в заявках на аккредитацию инспекторов',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inspectoraccreditationrequest',
            name='accreditation_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accreditation_requests', to='inspector_accreditation.AccreditationInspection', verbose_name='Задание на осмотр'),
        ),
    ]
