# Generated by Django 3.0.2 on 2023-04-12 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspector_accreditation', '0002_auto_20230411_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectoraccreditationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
