# Generated by Django 3.0.2 on 2023-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_accreditation', '0003_auto_20230412_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationinspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('dispatcher_check', 'На проверке у диспетчера'), ('troubleshooting', 'Устранение недочетов'), ('inspection_accepted', 'Осмотр принят')], default='draft', max_length=19, verbose_name='Статус осмотра'),
        ),
    ]
