# Generated by Django 3.0.2 on 2023-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_accreditation', '0004_auto_20230418_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationinspection',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
