# Generated by Django 3.0.2 on 2023-04-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20230209_1336'),
        ('inspector_accreditation', '0005_accreditationinspection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationinspection',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditation_inspections', to='address.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='inspectoraccreditationrequest',
            name='accreditation_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_requests', to='inspector_accreditation.AccreditationInspection', verbose_name='Задание на осмотр'),
        ),
    ]
