# Generated by Django 3.0.2 on 2022-07-27 15:03

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('product_code', 'Код товара'), ('product_name', 'Наименование товара'), ('title', 'Наименование товара для загрузки справочника'), ('price', 'Цена для загрузки справочника'), ('vendor_code', 'Код производителя'), ('additional_product_name_1', 'Доп. наименование товара 1'), ('additional_product_name_2', 'Доп. наименование товара 2'), ('additional_product_name_3', 'Доп. наименование товара 3'), ('product_price', 'Цена товара'), ('product_group', 'Группа товара'), ('trademark', 'Торговая марка'), ('size', 'Размер'), ('color', 'Цвет'), ('required_marking', 'Обязательная маркировка'), ('locked_date', 'Дата запрета оборота'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('name_sk', 'Название по ШК'), ('name_sk_1', 'Название по ШК 1'), ('name_sk_2', 'Название по ШК 2'), ('name_sk_3', 'Название по ШК 3'), ('price_sk', 'Цена по ШК'), ('excise_mark', 'Признак акцизной марки'), ('data_matrix', 'Признак DataMatrix'), ('zone_code', 'Код Зоны'), ('zone_name', 'Наименование Зоны'), ('storage_code', 'Код склада'), ('storage_place_code', 'Код места хранения'), ('storage_place_type', 'Тип места хранения'), ('remainder', 'Остаток'), ('remainder_2', 'Остаток 2'), ('pers_number', 'Табельный номер'), ('counter_status', 'Статус счётчика')], max_length=25, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
    ]
