# Generated by Django 3.0.2 on 2022-07-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20220727_1803'),
        ('template', '0002_auto_20220729_1116'),
    ]

    operations = [
    ]
