# Generated by Django 3.0.2 on 2024-03-14 10:34

import apps.helpers.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0019_auto_20240314_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('price', 'Цена товара'), ('remainder', 'Остаток'), ('remainder_2', 'Остаток 2'), ('measure', 'Единица измерения'), ('name_sk', 'Название по ШК'), ('am', 'Признак акцизной марки'), ('dm', 'ДатаМатрик(DataMatrix)'), ('zone_code', 'Код Зоны'), ('zone_name', 'Наименование Зоны'), ('store_number', 'Номер магазина')], max_length=12, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
        migrations.AlterField(
            model_name='templateexport',
            name='fields',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('zone_name', 'Наименование Зоны'), ('zone_number', 'Номер зоны'), ('barcode', 'Штрих-код'), ('barcode_x5', 'Штрих-код Х5'), ('vendor_code', 'Код товара'), ('title', 'Наименование товара'), ('price', 'Цена товара'), ('remainder_barcode', 'Остаток по штрихкоду'), ('discrepancy', 'Расхождение'), ('discrepancy_decimal', 'Расхождение с десятичной частью'), ('count_scanned_product', 'Количество отсканированных товаров'), ('count', 'Количество'), ('counter_code', 'Код счетчика'), ('data_matrix_code', 'Код DataMatrix'), ('store_number', 'Номер магазина')], max_length=21, verbose_name='Поле'), size=None, verbose_name='Список полей'),
        ),
    ]
