# Generated by Django 3.0.2 on 2024-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0025_templatefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatefield',
            options={'ordering': ('name',), 'verbose_name': 'Поле шаблона', 'verbose_name_plural': 'Поля шаблона'},
        ),
    ]
