# Generated by Django 3.0.2 on 2023-02-08 08:22

import apps.helpers.inn_validator
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='Название организации')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название')),
                ('inn', models.CharField(blank=True, default='', max_length=12, null=True, validators=[apps.helpers.inn_validator.inn_validator], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='ОГРН')),
                ('ogrnip', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='ОГРНИП')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Юридический адрес')),
                ('type', models.CharField(choices=[('legal', 'Юридическое лицо'), ('individual', 'Индивидуальный предприниматель')], default='individual', max_length=10, verbose_name='Тип организации')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Баланс')),
                ('inspectors', models.ManyToManyField(related_name='organizations', to='inspector.Inspector', verbose_name='Инспекторы')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
