# Generated by Django 3.0.2 on 2023-02-08 13:46

import apps.helpers.inn_validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='inspectors',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Юридическое название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[apps.helpers.inn_validator.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название организации'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Управляющий'), ('inspector', 'Инспектор')], max_length=9, verbose_name='Роль участника организации')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство пользователя в организации',
                'verbose_name_plural': 'Членства пользователей в организациях',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='organization.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
