# Generated by Django 3.0.2 on 2023-02-13 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_auto_20230210_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Пример, +79510549236', max_length=128, region=None, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Управляющий'), ('inspector', 'Инспектор')], max_length=9, verbose_name='Роль участника организации')),
                ('is_accepted', models.NullBooleanField(default=None, verbose_name='Принял/Отклонил')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_invitations', to='organization.Organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение на вступление в организацию',
                'verbose_name_plural': 'Приглашения на вступление в организацию',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
