# Generated by Django 3.0.2 on 2023-02-15 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_orginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='self_inspection_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=19, verbose_name='Цена за самостоятельный осмотр'),
        ),
    ]
