# Generated by Django 3.0.2 on 2023-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_self_inspection_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название организации'),
        ),
    ]
