# Generated by Django 3.0.2 on 2023-03-09 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0007_auto_20230221_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_invitations', to='organization.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
