# Generated by Django 3.0.2 on 2023-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20230309_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='self_inspection_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена за самостоятельный осмотр'),
        ),
    ]
