# Generated by Django 3.0.2 on 2023-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20230512_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная организация пользователя'),
        ),
    ]
