# Generated by Django 3.0.2 on 2023-06-23 09:51

import apps.helpers.inn_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_membership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[apps.helpers.inn_validator.inn_validator], verbose_name='ИНН'),
        ),
    ]
