# Generated by Django 3.0.2 on 2022-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=256, verbose_name='Название события')),
                ('comment', models.CharField(choices=[('for_the_client', 'Для заказчика')], default='for_the_client', max_length=14, verbose_name='Комментарий к событию')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('id',),
            },
        ),
    ]
