# Generated by Django 3.0.2 on 2022-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220415_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(max_length=256, verbose_name='Комментарий к событию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('for_the_client', 'Для заказчика'), ('products_catalog_load', 'Загружен справочник/каталог'), ('products_catalog_delete', 'Удален справочник/каталог'), ('zones_delete', 'Удалены зоны')], default='for_the_client', max_length=23, verbose_name='Название события'),
        ),
    ]
