# Generated by Django 3.0.2 on 2022-04-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20220414_1127'),
        ('event', '0003_auto_20220418_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('for_the_client', 'Для заказчика'), ('products_catalog_load', 'Загружен справочник/каталог'), ('products_catalog_delete', 'Удален справочник/каталог'), ('zones_delete', 'Удалены зоны'), ('create_new_project', 'Создан новый проект')], default='for_the_client', max_length=23, verbose_name='Название события'),
        ),
    ]
