# Generated by Django 3.0.2 on 2023-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_fake_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('for_the_client', 'Для заказчика'), ('products_catalog_load', 'Загружен справочник/каталог'), ('products_catalog_delete', 'Удален справочник/каталог'), ('zones_delete', 'Удалены зоны'), ('create_new_project', 'Создан новый проект'), ('project_settings_load', 'Загружены настройки проекта'), ('terminal_settings_update', 'Обновлены настройки терминала'), ('employees_delete', 'Удалены пользователи'), ('terminal_load_start', 'Запущен процесс загрузки терминалов'), ('exclude_zone_from_autoassignment', 'Исключена зона из автоназначения'), ('document_change_status', 'Изменен статус документа'), ('document_specification_editing', 'Измненение спецификации документа'), ('export_project_data', 'Выгрузка данных проекта'), ('export_template', 'Выгрузка шаблона'), ('change_template', 'Изменен шаблон'), ('update_articles', 'Обновление артикулов'), ('update_remainder', 'Обновление остатка'), ('import_project', 'Импорт проекта'), ('ready_terminal_db', 'Подготовка терминальной БД')], default='for_the_client', max_length=32, verbose_name='Название события'),
        ),
    ]
