# Generated by Django 3.0.2 on 2023-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Цвет'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
