# Generated by Django 3.0.2 on 2023-03-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_auto_20230309_1155'),
        ('car', '0002_auto_20230222_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
