# Generated by Django 3.0.2 on 2023-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20230309_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярная марка'),
        ),
        migrations.AddField(
            model_name='model',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярная модель'),
        ),
    ]
