# Generated by Django 3.0.2 on 2023-03-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_auto_20230329_1523'),
        ('car', '0005_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gov_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Гос.номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
