# Generated by Django 3.0.2 on 2023-04-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20230329_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'Марка транспорного средства', 'verbose_name_plural': 'Марки транспортных средств'},
        ),
    ]
