# Generated by Django 3.0.2 on 2023-04-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_accreditation', '0005_accreditationinspection_comment'),
        ('car', '0007_auto_20230406_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
    ]
