# Generated by Django 3.0.2 on 2023-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_accreditation_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность двигателя, л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем двигателя, см³'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
