# Generated by Django 3.0.2 on 2023-08-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20230809_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.FloatField(blank=True, null=True, verbose_name='Мощность двигателя, л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя, см³'),
        ),
    ]
