# Generated by Django 3.0.2 on 2023-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20230815_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(blank=True, null=True, verbose_name='Пробег'),
        ),
    ]
