# Generated by Django 3.0.2 on 2023-02-08 08:22

import apps.helpers.inn_validator
import apps.helpers.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('legal', 'Юридическое лицо'), ('individual', 'Индивидуальный предприниматель')], max_length=10, verbose_name='Роль'), size=None, verbose_name='Тип организации')),
                ('inn', models.CharField(blank=True, default='', max_length=12, null=True, validators=[apps.helpers.inn_validator.inn_validator], verbose_name='ИНН')),
                ('work_skills', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Опыт работы')),
                ('availability_thickness_gauge', models.BooleanField(default=True, verbose_name='Наличие толщиномера')),
                ('radius', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Радиус в км, в котором Инспектор получает заказы')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Баланс')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspectors', to='address.City', verbose_name='Город')),
                ('inspections', models.ManyToManyField(blank=True, related_name='inspectors', to='inspection.Inspection', verbose_name='Осмотры')),
            ],
            options={
                'verbose_name': 'Инспектор',
                'verbose_name_plural': 'Инспекторы',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
