# Generated by Django 3.0.2 on 2023-02-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspectors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
