# Generated by Django 3.0.2 on 2023-04-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_inspector_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='inspections',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='type',
        ),
    ]
