# Generated by Django 3.0.2 on 2023-04-20 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_auto_20230410_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account_number', models.CharField(max_length=31, verbose_name='Номер счета')),
                ('bank', models.CharField(max_length=31, verbose_name='Банк получателя')),
                ('bik', models.CharField(max_length=15, verbose_name='БИК')),
                ('inn', models.CharField(max_length=15, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=15, verbose_name='КПП')),
                ('correspondent_account', models.CharField(max_length=31, verbose_name='Корр.счет')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='inspector.Inspector')),
            ],
            options={
                'verbose_name': 'Реквизиты инспектора',
                'verbose_name_plural': 'Реквизиты инспектора',
                'ordering': ('-created_at',),
            },
        ),
    ]
