# Generated by Django 3.0.2 on 2023-04-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_requisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisite',
            name='inspector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='inspector.Inspector'),
        ),
    ]
