# Generated by Django 3.0.2 on 2023-04-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_auto_20230420_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisite',
            name='inspector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisite', to='inspector.Inspector'),
        ),
    ]
