# Generated by Django 3.0.2 on 2023-08-01 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspector', '0006_auto_20230421_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
