# Generated by Django 3.0.2 on 2023-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_auto_20230801_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisite',
            name='bank',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Банк получателя'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Корр.счет'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='КПП'),
        ),
    ]
