# Generated by Django 3.0.2 on 2023-02-08 08:22

import apps.helpers.managers
import apps.helpers.model_fields
import apps.helpers.sms
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('username', models.CharField(blank=True, default='', max_length=40, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=40, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Пример, +79510549236', max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('confirm_registration', models.BooleanField(default=False, verbose_name='Подтверждение регистрации')),
                ('agreement_policy', models.BooleanField(default=False, verbose_name='Согласие с условиями политики конфиденциальности')),
                ('agreement_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('inspector_mode', models.BooleanField(default=False, verbose_name='Режим инспектора')),
                ('role', apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('Inspection customer', 'Заказчик осмотра'), ('Free inspector', 'Свободный инспектор'), ('Organization Inspector', 'Инспектор организации'), ('Dispatcher', 'Диспетчер'), ('Administrator', 'Администратор')], default='Inspection customer', max_length=22, verbose_name='Роли пользователя'), default=['Inspection customer'], size=None, verbose_name='Роли пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('email',),
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', apps.helpers.managers.CustomFieldUserManager(username_field_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Пример, +79510549236', max_length=128, region=None, verbose_name='Номер телефона')),
                ('code', models.CharField(default=apps.helpers.sms.gen_code, editable=False, max_length=4, verbose_name='Код')),
                ('expire', models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Время жизни')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Код для регистрации',
                'verbose_name_plural': 'Коды для регистраций',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('code', models.CharField(default=apps.helpers.sms.gen_code, editable=False, max_length=4, verbose_name='Код')),
                ('expire', models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Время жизни')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
