# Generated by Django 3.0.2 on 2023-02-08 14:51

import apps.helpers.model_fields
import apps.user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inspector_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=apps.helpers.model_fields.ChoiceArrayField(base_field=models.CharField(choices=[('customer', 'Заказчик'), ('inspector', 'Инспектор'), ('Dispatcher', 'Диспетчер'), ('Administrator', 'Администратор')], default='customer', max_length=13, verbose_name='Роль'), default=apps.user.models.user.get_default_role, size=None, verbose_name='Роли'),
        ),
    ]
