# Generated by Django 3.0.2 on 2023-02-27 08:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationCode',
        ),
        migrations.RemoveField(
            model_name='confirmationcode',
            name='status',
        ),
        migrations.RemoveField(
            model_name='confirmationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Пример, +79510549236', max_length=128, region=None, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
