# Generated by Django 3.0.2 on 2023-02-28 07:03

import apps.user.models.confirmation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230227_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_registration',
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='expired_datetime',
            field=models.DateTimeField(default=apps.user.models.confirmation.calculate_expired_datetime, verbose_name='Дата и время окончания жизни кода'),
        ),
    ]
