# Generated by Django 3.0.2 on 2023-01-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20211007_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='job_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
