# Generated by Django 3.0.2 on 2023-02-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0001_initial'),
        ('inspection_task', '0001_initial'),
        ('organization', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор осмотра'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organization.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sign_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='file.Image', verbose_name='Подпись клиента'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sign_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sign_inspectors', to='file.Image', verbose_name='Подпись инспектора'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspection_task.InspectionTask', verbose_name='Задание на осмотр'),
        ),
        migrations.AddField(
            model_name='document',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='damagecheck',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='damage_checks', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='completeness',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completeness', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='complectation',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complectations', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='client',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='anotherdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='another_documents', to='inspection.Document', verbose_name='Документы'),
        ),
    ]
