# Generated by Django 3.0.2 on 2023-02-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20230214_1439'),
        ('inspection', '0003_inspection_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='template.Template', verbose_name='Шаблон осмотра'),
        ),
    ]
