# Generated by Django 3.0.2 on 2023-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20230214_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
