# Generated by Django 3.0.2 on 2023-02-22 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspection_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ptsdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='stsdocument',
            name='document',
        ),
        migrations.DeleteModel(
            name='TypeAnotherDocument',
        ),
        migrations.AddField(
            model_name='document',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран'),
        ),
        migrations.DeleteModel(
            name='AnotherDocument',
        ),
        migrations.DeleteModel(
            name='PTSDocument',
        ),
        migrations.DeleteModel(
            name='STSDocument',
        ),
    ]
