# Generated by Django 3.0.2 on 2023-02-22 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0007_auto_20230221_1733'),
        ('inspection', '0006_auto_20230222_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор осмотра'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organization.Organization', verbose_name='Организация'),
        ),
    ]
