# Generated by Django 3.0.2 on 2023-02-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20230214_1439'),
        ('inspection', '0007_auto_20230222_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='template.Template', verbose_name='Шаблон осмотра'),
        ),
    ]
