# Generated by Django 3.0.2 on 2023-03-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_auto_20230227_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='document',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='video',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
