# Generated by Django 3.0.2 on 2023-03-09 08:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_auto_20230307_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='damage', to='inspection.Inspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Проверка повреждений',
                'verbose_name_plural': 'Проверки повреждений',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран')),
                ('inspection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inspection.Inspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Комплектация автомобиля',
                'verbose_name_plural': 'Комплектации автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lift', to='inspection.Inspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Осмотр на подъемнике',
                'verbose_name_plural': 'Осмотр на подъемнике',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='technical', to='inspection.Inspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Техническое состояние',
                'verbose_name_plural': 'Технические состояния',
            },
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photos',
        ),
        migrations.RenameModel(
            old_name='Tire',
            new_name='Tires',
        ),
        migrations.RemoveField(
            model_name='damagecheck',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='liftinspection',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='technicalstate',
            name='inspection',
        ),
        migrations.AlterField(
            model_name='client',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='document',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='paintwork',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paintwork', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='video',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.DeleteModel(
            name='Complectation',
        ),
        migrations.DeleteModel(
            name='DamageCheck',
        ),
        migrations.DeleteModel(
            name='LiftInspection',
        ),
        migrations.DeleteModel(
            name='TechnicalState',
        ),
    ]
