# Generated by Django 3.0.2 on 2023-03-09 10:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_auto_20230309_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Ответ на экран')),
                ('inspection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='inspection.Inspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
