# Generated by Django 3.0.2 on 2023-03-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_auto_20230309_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ('-created_at',), 'verbose_name': 'Осмотр', 'verbose_name_plural': 'Осмотры'},
        ),
    ]
