# Generated by Django 3.0.2 on 2023-04-13 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('inspection', '0014_auto_20230329_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signs_inspector', to='file.Image', verbose_name='Подпись клиента')),
            ],
            options={
                'verbose_name': 'Подпись инспектора',
                'verbose_name_plural': 'Подписи инспекторов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SignClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signs_client', to='file.Image', verbose_name='Подпись клиента')),
            ],
            options={
                'verbose_name': 'Подпись клиента',
                'verbose_name_plural': 'Подписи клиентов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='inspection',
            name='sign_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspection.SignClient', verbose_name='Подпись клиента'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='sign_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspection.SignInspector', verbose_name='Подпись инспектора'),
        ),
    ]
