# Generated by Django 3.0.2 on 2023-04-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0016_auto_20230413_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signclient',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_client', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='signinspector',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_inspector', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
