# Generated by Django 3.0.2 on 2023-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0017_auto_20230413_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='complete_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
    ]
