# Generated by Django 3.0.2 on 2023-04-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_accreditation', '0005_accreditationinspection_comment'),
        ('inspection', '0018_auto_20230414_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='completeness',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completeness', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='damage',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='documents',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='lift',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lift', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='paintwork',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paintwork', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='photos',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='signclient',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_client', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='signinspector',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_inspector', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='technical',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='tires',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
        migrations.AddField(
            model_name='video',
            name='accreditation_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='inspector_accreditation.AccreditationInspection', verbose_name='Осмотр на аккредитацию'),
        ),
    ]
