# Generated by Django 3.0.2 on 2023-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0019_auto_20230419_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='type',
            field=models.CharField(choices=[('self_inspection', 'Самостоятельный'), ('by_task', 'По заданию'), ('by_task_with_organization_inspector', 'По заданию с инспектором организации')], default='self_inspection', max_length=35, verbose_name='Тип'),
        ),
    ]
