# Generated by Django 3.0.2 on 2023-06-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0020_inspection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lift', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='paintwork',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paintwork', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='tires',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
