# Generated by Django 3.0.2 on 2023-06-21 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0021_auto_20230616_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('complete', 'Завершен'), ('troubleshooting', 'Устранение недочетов'), ('draft', 'Черновик')], default='draft', max_length=15, verbose_name='Статус осмотра'),
        ),
        migrations.CreateModel(
            name='InspectionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('text', models.TextField(verbose_name='Текст замечания')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inspection.Inspection')),
            ],
            options={
                'verbose_name': 'Замечание по осмотру',
                'verbose_name_plural': 'Замечания по осмотру',
                'ordering': ('-created_at',),
            },
        ),
    ]
