# Generated by Django 3.0.2 on 2023-06-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0022_auto_20230621_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionnote',
            options={'ordering': ('-created_at',), 'verbose_name': 'Замечание по осмотру', 'verbose_name_plural': 'Замечания по осмотрам'},
        ),
    ]
