# Generated by Django 3.0.2 on 2023-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0023_auto_20230622_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('complete', 'Завершен'), ('troubleshooting', 'Устранение недочетов'), ('under_review', 'На проверке'), ('draft', 'Черновик')], default='draft', max_length=15, verbose_name='Статус осмотра'),
        ),
    ]
