# Generated by Django 3.0.2 on 2023-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0024_auto_20230710_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('complete', 'Завершен'), ('troubleshooting', 'Устранение недочетов'), ('accepted', 'Принят'), ('draft', 'Черновик')], default='draft', max_length=15, verbose_name='Статус осмотра'),
        ),
    ]
