# Generated by Django 3.0.2 on 2023-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0025_auto_20230713_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('complete', 'Завершен'), ('troubleshooting', 'Устранение недочетов'), ('under_review', 'На проверке'), ('accepted', 'Принят'), ('draft', 'Черновик')], default='draft', max_length=15, verbose_name='Статус осмотра'),
        ),
    ]
