# Generated by Django 3.0.2 on 2023-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0026_auto_20230713_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='fake_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален только для фронта'),
        ),
    ]
