# Generated by Django 3.0.2 on 2022-04-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0012_delete_task'),
        ('employee', '0007_delete_workresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('ready', 'Готова'), ('not_ready', 'Не готова')], default='not_ready', max_length=9, verbose_name='Статус')),
                ('start_audit_date', models.DateField(verbose_name='Начало аудита')),
                ('end_audit_date', models.DateField(verbose_name='Окончание аудита')),
                ('tsd_number', models.IntegerField(verbose_name='№ ТСД')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.Employee', verbose_name='Сотрудник')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='zone.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-created_at',),
            },
        ),
    ]
