# Generated by Django 3.0.2 on 2022-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220331_1233'),
        ('document', '0003_auto_20220415_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='task.Task', verbose_name='Таска'),
        ),
    ]
