# Generated by Django 3.0.2 on 2022-05-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0012_delete_task'),
        ('document', '0004_document_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='task',
        ),
        migrations.AlterField(
            model_name='document',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='zone.Zone', verbose_name='Зона'),
        ),
    ]
