# Generated by Django 3.0.2 on 2022-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20220824_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='end_audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание аудита'),
        ),
        migrations.AlterField(
            model_name='document',
            name='start_audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало аудита'),
        ),
    ]
