# Generated by Django 3.0.2 on 2022-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20220830_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('green', 'Зеленый'), ('red', 'Красный'), ('gray', 'Серый'), ('orange', 'Оранжевый'), ('blue', 'Голубой'), ('violet', 'Фиолетовый')], default='red', max_length=6, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='document',
            name='color_changed',
            field=models.BooleanField(default=False),
        ),
    ]
