# Generated by Django 3.0.2 on 2023-01-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20221108_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='employee_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='zone_title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
