# Generated by Django 3.0.2 on 2023-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20230120_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fake_id',
            field=models.IntegerField(default=1),
        ),
    ]
