# Generated by Django 3.0.2 on 2023-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_document_fake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prev_color',
            field=models.CharField(blank=True, choices=[('green', 'Зеленый'), ('red', 'Красный'), ('gray', 'Серый'), ('orange', 'Оранжевый'), ('blue', 'Голубой'), ('violet', 'Фиолетовый'), ('white', 'Белый')], default=None, max_length=6, null=True),
        ),
    ]
