# Generated by Django 3.0.2 on 2023-10-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20231024_1853'),
        ('document', '0018_document_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='auditor_controller_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_controller_document', to='task.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='auditor_scan_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_scan_document', to='task.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='counter_controller_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_controller_document', to='task.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='counter_scan_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_scan_document', to='task.Task'),
        ),
    ]
