# Generated by Django 3.0.2 on 2024-02-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20240207_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_replace_specification',
            field=models.BooleanField(default=False, verbose_name='Замена спецификации'),
        ),
    ]
