# Generated by Django 3.0.2 on 2023-02-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('inspection_task', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='inspection_task.InspectionTask', verbose_name='Задание на осмотр'),
        ),
        migrations.AddField(
            model_name='inspectiontasksearch',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_task_search', to='inspection_task.InspectionTask', verbose_name='Задание на осмотр'),
        ),
        migrations.AddField(
            model_name='inspectiontaskcar',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='inspection_task.InspectionTask', verbose_name='Задание на осмотр'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='address.Address', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspector_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор осмотра'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='organization.Organization', verbose_name='Организация'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectiontaskcar',
            unique_together={('serial_number', 'task')},
        ),
    ]
