# Generated by Django 3.0.2 on 2023-03-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20230309_1204'),
        ('inspection_task', '0002_auto_20230208_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectiontaskcar',
            old_name='vin',
            new_name='vin_code',
        ),
        migrations.RemoveField(
            model_name='inspectiontaskcar',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='inspectiontaskcar',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Category', verbose_name='Тип ТС'),
        ),
        migrations.AlterField(
            model_name='inspectiontaskcar',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='inspectiontaskcar',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Model', verbose_name='Модель'),
        ),
    ]
