# Generated by Django 3.0.2 on 2023-03-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20230309_1204'),
        ('inspection_task', '0003_auto_20230310_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontasksearch',
            options={'verbose_name': 'Объект поиска инспекторов', 'verbose_name_plural': 'Объекты поиска инспекторов'},
        ),
        migrations.AlterField(
            model_name='inspectiontaskcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='inspectiontaskcar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Category', verbose_name='Тип ТС'),
        ),
        migrations.AlterField(
            model_name='inspectiontaskcar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='car.Model', verbose_name='Модель'),
        ),
    ]
