# Generated by Django 3.0.2 on 2023-03-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20230209_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20230309_1208'),
        ('inspection_task', '0004_auto_20230310_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='accepted_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время принятия задания'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='planed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата осмотра'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='planed_date_confirm',
            field=models.BooleanField(default=False, verbose_name='Дата осмотра подтверждена'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_tasks', to='address.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор осмотра'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_tasks', to='organization.Organization', verbose_name='Организация'),
        ),
    ]
