# Generated by Django 3.0.2 on 2023-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0005_auto_20230314_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontask',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('inspector_search', 'Поиск инспектора'), ('task_accepted', 'Задание принято'), ('inspection_appointed', 'Назначен осмотр'), ('inspection_date_confirmed', 'Дата осмотра подтверждена'), ('troubleshooting', 'Устранение недочетов'), ('paid', 'Оплачено')], default='draft', max_length=25, verbose_name='Статус'),
        ),
    ]
