# Generated by Django 3.0.2 on 2023-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0006_auto_20230515_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='type',
            field=models.CharField(choices=[('for_search_inspector', 'Для поиска инспектора'), ('for_appointment', 'Для назначения инспектора организации')], default='for_search_inspector', max_length=20, verbose_name='Тип'),
        ),
    ]
