# Generated by Django 3.0.2 on 2023-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0007_inspectiontask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontaskcar',
            name='unstandart_vin',
            field=models.BooleanField(default=False, verbose_name='Нестандартный VIN'),
        ),
    ]
