# Generated by Django 3.0.2 on 2023-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0008_inspectiontaskcar_unstandart_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='last_status_change_date',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения статуса'),
        ),
    ]
