# Generated by Django 3.0.2 on 2023-06-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0021_auto_20230616_1223'),
        ('inspection_task', '0009_inspectiontask_last_status_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontaskcar',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_task_cars', to='inspection.Inspection', verbose_name='Осмотр'),
        ),
    ]
