# Generated by Django 3.0.2 on 2023-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0010_inspectiontaskcar_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontaskcar',
            name='fake_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено для фронта'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('inspector_search', 'Поиск инспектора'), ('task_accepted', 'Задание принято'), ('inspection_appointed', 'Назначен осмотр'), ('inspection_date_confirmed', 'Дата осмотра подтверждена'), ('troubleshooting', 'Устранение недочетов'), ('inspection_done', 'Осмотр выполнен'), ('paid', 'Оплачено')], default='draft', max_length=25, verbose_name='Статус'),
        ),
    ]
