# Generated by Django 3.0.2 on 2023-07-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0011_auto_20230719_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontaskcar',
            name='fake_deleted',
        ),
    ]
