# Generated by Django 3.0.2 on 2023-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_task', '0012_remove_inspectiontaskcar_fake_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='is_accrual',
            field=models.BooleanField(default=False, verbose_name='Начислено инспектору'),
        ),
    ]
