# Generated by Django 3.0.2 on 2023-08-01 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection_task', '0013_inspectiontask_is_accrual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор'),
        ),
    ]
