# Generated by Django 3.0.2 on 2022-02-24 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_task', models.CharField(blank=True, choices=[('least_loaded_user', 'Наименее загруженному пользователю'), ('current_user', 'Текущему пользователю')], max_length=17, null=True, verbose_name='Выдача задания для УК')),
                ('length_barcode_pallets', models.CharField(blank=True, max_length=30, null=True, verbose_name='Длина ШК Паллеты')),
                ('error_correction', models.NullBooleanField(verbose_name='Исправление ошибок')),
                ('compliance_codes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коды соответствия ШК х5')),
                ('product_name', models.CharField(blank=True, choices=[('by_product_code', 'По коду товара'), ('by_barcode', 'По штрих-коду')], max_length=15, null=True, verbose_name='Наименование товара')),
                ('unknown_barcode', models.CharField(blank=True, choices=[('allow', 'Разрешать'), ('disallow', 'Запрещать')], max_length=8, null=True, verbose_name='Неизвестный штрих-код')),
                ('trimming_barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Обрезка штрих-кода с начала и с конца')),
                ('recalculation_discrepancy', models.CharField(blank=True, choices=[('scan', 'Скан'), ('controller', 'УК')], max_length=10, null=True, verbose_name='Пересчет при расхождении')),
                ('suspicious_barcodes_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Подозрительное кол-во для ШК')),
                ('check_dm', models.CharField(blank=True, choices=[('without_dm_check', 'Без проверки DM'), ('only_dm_check', 'Только наличие DM'), ('conformity_dm', 'Соответствие DM и ШК')], max_length=16, null=True, verbose_name='Проверка DM')),
                ('check_am', models.CharField(blank=True, choices=[('without_dm_check', 'Без проверки AM'), ('only_dm_check', 'Только наличие AM'), ('conformity_am', 'Соответствие AM и ШК')], max_length=16, null=True, verbose_name='Проверка АМ')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_settings', to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Настройки параметров терминала',
                'verbose_name_plural': 'Настройки параметров терминала',
            },
        ),
    ]
