# Generated by Django 3.0.2 on 2022-02-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
        ('project', '0003_auto_20220224_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='template.Template', verbose_name='Шаблон'),
        ),
    ]
