# Generated by Django 3.0.2 on 2022-04-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
        ('project', '0006_auto_20220325_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='template.Template', verbose_name='Шаблон'),
        ),
    ]
