# Generated by Django 3.0.2 on 2022-07-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_merge_20220729_1217'),
        ('project', '0007_auto_20220414_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='template.TemplateExport', verbose_name='Шаблон выгрузки'),
        ),
    ]
