# Generated by Django 3.0.2 on 2022-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_template_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='search_by_product_code',
            field=models.BooleanField(default=False, verbose_name='Поиск по коду товара'),
        ),
    ]
