# Generated by Django 3.0.2 on 2022-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20221123_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_assign_enbale',
            field=models.BooleanField(default=False, verbose_name='Включено автоназнаение задач С.Скан'),
        ),
    ]
