# Generated by Django 3.0.2 on 2023-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_accounting_without_yk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='auto_assign_enbale',
            field=models.BooleanField(default=False, verbose_name='Включено автоназначение задач для Скан'),
        ),
    ]
