# Generated by Django 3.0.2 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20231110_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmmsettings',
            name='password',
            field=models.CharField(default='555', max_length=10, verbose_name='Пароль для редактирования настроек'),
        ),
    ]
