# Generated by Django 3.0.2 on 2024-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_terminalsettings_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalsettings',
            name='check_dm',
            field=models.CharField(choices=[('without_dm_check', 'Без проверки DM'), ('only_dm_check', 'Только наличие DM'), ('conformity_dm', 'Соответствие DM и ШК'), ('binding_dm', 'Привязка DM к ШК')], default='without_dm_check', max_length=16, verbose_name='Проверка DM'),
        ),
    ]
