# Generated by Django 3.0.2 on 2024-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_auto_assign_enbale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalsettings',
            name='password',
            field=models.CharField(default='7467253', max_length=10, verbose_name='Пароль редактирования'),
        ),
    ]
