# Generated by Django 3.2 on 2024-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20240131_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsettings',
            name='is_scanning_of_weight_product',
            field=models.BooleanField(default=False, verbose_name='Сканирования весового товара'),
        ),
    ]
