# Generated by Django 3.0.2 on 2022-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('project', 'serial_number'), name='Порядковый номер зоны в рамках проекта'),
        ),
    ]
