# Generated by Django 3.0.2 on 2022-03-04 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220302_1750'),
        ('zone', '0002_auto_20220303_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='employees',
        ),
        migrations.AddField(
            model_name='zone',
            name='is_auto_assignment',
            field=models.BooleanField(default=True, verbose_name='Автоназначение'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', models.CharField(choices=[('counter_scan', 'С.Скан'), ('counter_controller', 'С.УК'), ('auditor_scan', 'А.Скан'), ('auditor_controller', 'А.УК'), ('storage', 'Сотрудник склада')], max_length=18, verbose_name='Тип')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employee.Employee', verbose_name='Сотрудник')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='zone.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('-created_at',),
            },
        ),
    ]
