# Generated by Django 3.0.2 on 2022-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_task_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('zone', 'employee', 'type'), name='Задание с определенным типом сотрудника на зоне'),
        ),
    ]
