# Generated by Django 3.0.2 on 2022-03-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0011_task_terminal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
