# Generated by Django 3.0.2 on 2022-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0012_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='serial_number',
            field=models.CharField(default='', max_length=31, verbose_name='Порядковый номер'),
        ),
    ]
