# Generated by Django 3.0.2 on 2022-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0014_auto_20220810_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Код зоны'),
        ),
    ]
