# Generated by Django 3.0.2 on 2023-02-08 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('error', 'Ошибка'), ('done', 'Завершена')], default='pending', max_length=7, verbose_name='Статус')),
                ('type', models.CharField(choices=[('add', 'Начисление'), ('withdraw', 'Списание')], max_length=8, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма транзакции')),
                ('operation', models.CharField(choices=[('completed_task', 'Начисление за выполненное задание'), ('withdraw_to_card', 'Вывод средств на карту')], max_length=16, verbose_name='Название операции')),
            ],
            options={
                'verbose_name': 'Транзакция инспектора',
                'verbose_name_plural': 'Транзакции инспектора',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('error', 'Ошибка'), ('done', 'Завершена')], default='pending', max_length=7, verbose_name='Статус')),
                ('type', models.CharField(choices=[('add', 'Начисление'), ('withdraw', 'Списание')], max_length=8, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма транзакции')),
                ('operation', models.CharField(choices=[('balance_replenishment', 'Пополнение баланса'), ('self_inspection', 'Списание за самостоятельный осмотр'), ('inspection_task', 'Списание за задание на осмотр'), ('refund_canceled_task', 'Возврат за отмененное задание'), ('payment_tariff', 'Оплата по тарифу')], max_length=21, verbose_name='Название операции')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organization.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Транзакция организации',
                'verbose_name_plural': 'Транзакции организации',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
