# Generated by Django 3.0.2 on 2023-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20230208_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtransaction',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL адреса страницы оплаты'),
        ),
    ]
