# Generated by Django 3.0.2 on 2023-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_organizationtransaction_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectortransaction',
            name='type',
            field=models.CharField(choices=[('add', 'Начисление'), ('hand_add', 'Ручное начисление'), ('withdraw', 'Списание'), ('hand_withdraw', 'Ручное списание')], max_length=13, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='organizationtransaction',
            name='operation',
            field=models.CharField(choices=[('balance_replenishment', 'Пополнение баланса'), ('hand_balance_replenishment', 'Ручное списание с баланса'), ('hand_balance_write_off', 'Ручное зачисление в баланс'), ('self_inspection', 'Списание за самостоятельный осмотр'), ('inspection_task', 'Списание за задание на осмотр'), ('refund_canceled_task', 'Возврат за отмененное задание'), ('payment_tariff', 'Оплата по тарифу')], max_length=26, verbose_name='Название операции'),
        ),
        migrations.AlterField(
            model_name='organizationtransaction',
            name='type',
            field=models.CharField(choices=[('add', 'Начисление'), ('hand_add', 'Ручное начисление'), ('withdraw', 'Списание'), ('hand_withdraw', 'Ручное списание')], max_length=13, verbose_name='Тип'),
        ),
    ]
