# Generated by Django 3.0.2 on 2023-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20230613_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectortransaction',
            name='type',
            field=models.CharField(choices=[('add', 'Начисление'), ('withdraw', 'Списание')], max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='organizationtransaction',
            name='operation',
            field=models.CharField(choices=[('balance_replenishment', 'Пополнение баланса'), ('hand_balance_replenishment', 'Ручное зачисление в баланс'), ('hand_balance_withdraw', 'Ручное списание с баланса'), ('self_inspection', 'Списание за самостоятельный осмотр'), ('inspection_task', 'Списание за задание на осмотр'), ('refund_canceled_task', 'Возврат за отмененное задание'), ('payment_tariff', 'Оплата по тарифу')], max_length=26, verbose_name='Название операции'),
        ),
        migrations.AlterField(
            model_name='organizationtransaction',
            name='type',
            field=models.CharField(choices=[('add', 'Начисление'), ('withdraw', 'Списание')], max_length=8, verbose_name='Тип'),
        ),
    ]
