# Generated by Django 3.0.2 on 2023-08-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_auto_20230801_1229'),
        ('transaction', '0005_auto_20230616_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectortransaction',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inspector.Inspector', verbose_name='Инспектор'),
        ),
    ]
