# Generated by Django 5.0.4 on 2024-09-03 12:20

import apps.helpers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0001_initial'),
        ('file', '0002_image'),
        ('projects', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePromotionMailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('publish_datetime', models.DateTimeField(verbose_name='Время публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_push', models.BooleanField(default=False, verbose_name='Отправка пуша')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PromotionMailingUserRole',
            fields=[
                ('basepromotionmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.basepromotionmailing')),
                ('roles', apps.helpers.models.ChoiceArrayField(base_field=models.CharField(choices=[('applicant', 'Аппликант'), ('employee', 'Сотрудник'), ('supervisor', 'Супервайзер')], max_length=10, verbose_name='Роль'), size=None, verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Рассылка акций по ролям',
                'verbose_name_plural': 'Рассылки акций по ролям',
            },
            bases=('promotion.basepromotionmailing',),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('just_promotion', 'Обычная акция'), ('contest', 'Конкурс'), ('draw', 'Розыгрыш')], max_length=14, verbose_name='Тип')),
                ('is_top', models.BooleanField(default=False, verbose_name='Закрепленная акция')),
                ('is_main_display', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('attachments', models.ManyToManyField(related_name='promotions', to='file.file', verbose_name='Вложения')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='file.image', verbose_name='Обложка, в формате png')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='basepromotionmailing',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='promotion.promotion', verbose_name='Акция'),
        ),
        migrations.CreateModel(
            name='PromotionMailingDepartment',
            fields=[
                ('basepromotionmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.basepromotionmailing')),
                ('departments', models.ManyToManyField(related_name='mailings', to='departments.department', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Рассылка акций по департаментам',
                'verbose_name_plural': 'Рассылки акций по департаментам',
            },
            bases=('promotion.basepromotionmailing',),
        ),
        migrations.CreateModel(
            name='PromotionMailingProject',
            fields=[
                ('basepromotionmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.basepromotionmailing')),
                ('projects', models.ManyToManyField(related_name='mailings', to='projects.project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Рассылка акций по проектам',
                'verbose_name_plural': 'Рассылки акций по проектам',
            },
            bases=('promotion.basepromotionmailing',),
        ),
        migrations.CreateModel(
            name='PromotionMailingRegion',
            fields=[
                ('basepromotionmailing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.basepromotionmailing')),
                ('regions', models.ManyToManyField(related_name='mailings', to='regions.region', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Рассылка акций по регионам',
                'verbose_name_plural': 'Рассылки акций по регионам',
            },
            bases=('promotion.basepromotionmailing',),
        ),
    ]
