# Generated by Django 5.0.4 on 2024-09-03 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepromotionmailing',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('-created_at',), 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='promotionmailingdepartment',
            options={'base_manager_name': 'objects', 'verbose_name': 'Рассылка акций по департаментам', 'verbose_name_plural': 'Рассылки акций по департаментам'},
        ),
        migrations.AlterModelOptions(
            name='promotionmailingproject',
            options={'base_manager_name': 'objects', 'verbose_name': 'Рассылка акций по проектам', 'verbose_name_plural': 'Рассылки акций по проектам'},
        ),
        migrations.AlterModelOptions(
            name='promotionmailingregion',
            options={'base_manager_name': 'objects', 'verbose_name': 'Рассылка акций по регионам', 'verbose_name_plural': 'Рассылки акций по регионам'},
        ),
        migrations.AlterModelOptions(
            name='promotionmailinguserrole',
            options={'base_manager_name': 'objects', 'verbose_name': 'Рассылка акций по ролям', 'verbose_name_plural': 'Рассылки акций по ролям'},
        ),
        migrations.CreateModel(
            name='PromotionEmoji',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('emoji_type', models.CharField(choices=[('smirk', 'Ухмылка'), ('thumb_up', 'Палец вверх'), ('thumb_down', 'Палец вниз'), ('fire', 'Огонь'), ('heart', 'Сердце'), ('shock', 'Удивление')], max_length=10, verbose_name='Тип эмодзи')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_emoji', to='promotion.promotion', verbose_name='Акция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_emoji', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эмодзи акций',
                'verbose_name_plural': 'Эмодзи акций',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='promotionemoji',
            constraint=models.UniqueConstraint(fields=('promotion', 'user'), name='Эмодзи юзера на акцию'),
        ),
    ]
