# Generated by Django 5.0.4 on 2024-09-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_image'),
        ('promotion', '0003_promotionread_promotionread_просмотр_юзером_акции'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='cover',
        ),
        migrations.AddField(
            model_name='promotion',
            name='preview_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_main_promotion', to='file.image', verbose_name='Превью для главной'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='preview_standart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_standart_promotion', to='file.image', verbose_name='Превью стандарт'),
        ),
    ]
