# Generated by Django 5.0.4 on 2024-10-09 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_alter_promotionmailinguserrole_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepromotionmailing',
            name='publish_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
    ]
