# Generated by Django 5.0.4 on 2024-08-30 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_image'),
        ('news', '0004_newsread_newsread_просмотр_новости_пользователем'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('background_color_button', models.CharField(blank=True, max_length=40, null=True, verbose_name='Цвет кнопки')),
                ('text_color', models.CharField(blank=True, max_length=40, null=True, verbose_name='Цвет текста')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='news.news', verbose_name='Новости')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_stories', to='file.image', verbose_name='Превью')),
                ('slides', models.ManyToManyField(blank=True, related_name='slides_stories', to='file.image', verbose_name='Слайды')),
            ],
            options={
                'verbose_name': 'Сторис',
                'verbose_name_plural': 'Сторисы',
            },
        ),
    ]
