# Generated by Django 5.0.4 on 2024-08-30 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_basestoriesmailing_storiesmailinguserrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Удален')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_read', to='stories.stories', verbose_name='Сторис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_read', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотренная сторис',
                'verbose_name_plural': 'Просмотренные сторисы',
            },
        ),
        migrations.AddConstraint(
            model_name='storiesread',
            constraint=models.UniqueConstraint(fields=('stories', 'user'), name='Просмотр сторис пользователем'),
        ),
    ]
