# Generated by Django 5.0.4 on 2024-09-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storiesread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='text_button',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Текст кнопки'),
        ),
    ]
