# Generated by Django 5.0.4 on 2024-10-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_storiesmailingregion_to_all_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Закрепленная сторис'),
        ),
    ]
